### ISSUE TITLE
fig.align command doesn't work in html_clean

### ISSUE THREAD

**Issue by megaraptor1** [juba/rmdformats#100]
Was working some more with the html_clean format and I found that the command for left or right-aligning the figure caption does not work with this format. The figure caption is always centered and giving the command to manually change it does not work. I did some more testing and it is only present in html_clean, it is not in the base html_document (I did not check the other formats).

Below is some code that was able to replicate this error.

---
output:
  rmdformats::html_clean
---

```{r fig.cap="fig1",fig.align="left"}
library(ggplot2)
data(mtcars)
ggplot(mtcars,aes(cyl,mpg))+
geom_point()
```

**Comment by juba** [comment]
Yes, you're right. Should be fixed now.
