### ISSUE TITLE
Add icons on templates

### ISSUE THREAD

**Issue by camilogarciabotero** [juba/rmdformats#101]
Hi all,

Thanks for your work on these templates! I've found them so great. I was wondering if it is possible to have icons on the templates such as the Github icon as a circle icon or as a corner icon flag... or an Orcid, Twitter icon anywhere.

Thanks,
Camilo.

**Comment by juba** [comment]
Hi,

I'm not sure what you're asking for precisely ? Do you mean the way to easily insert a Github or Twitter icon with a framework such as Font awesome ? Or an option that would put such an icon somewhere in the template ?

**Comment by camilogarciabotero** [comment]
HI @juba,

Sorry for not being more clear before. I was wonder if I can add a GitHub, Twitter, Orcid or way other icon from the YAML header, that will appear in the theme. Like in this example: 

![Screen Shot 2021-04-01 at 9 06 02 AM](https://user-images.githubusercontent.com/25586362/113306252-8016ed00-92c9-11eb-9a22-944c8949411a.png)

Or well as a corner icon flag (for the case of github):

![Screen Shot 2021-04-01 at 9 05 21 AM](https://user-images.githubusercontent.com/25586362/113306160-670e3c00-92c9-11eb-8e99-f13308512311.png)

In those cases, I just add the respective information on the YAML header of the theme I used.

Thanks,
Camilo.

**Comment by juba** [comment]
I see... Unfortunately no, there is no way in `rmdformats` templates to add these logos based on metadata in the YAML preamble. The only way is to add them manually in the document content.

**Comment by camilogarciabotero** [comment]
Oh, I see.

Thanks @juba

**Comment by juba** [comment]
Just for your information (sorry if you already know it), you can add HTML to an Rmarkdown document, so you can do something like the following to add a github logo with a link in the corner : 

```html
<div style="position: fixed; top: 0; right: 0;">
  <a href="https://github.com">
    <img src="https://user-images.githubusercontent.com/25586362/113306160-670e3c00-92c9-11eb-8e99-f13308512311.png" />
  </a>
</div>
```
