### ISSUE TITLE
Is there a way to disable lightbox for particular images ?

### ISSUE THREAD

**Issue by Lucius-Cesar** [juba/rmdformats#102]
Hello, 
First of all thanks for maintaining this really useful package.

I have images associate with a link and a logo in my project and I didn't find a way to selectively disable the lightbox view for these particular cases. Is there a way to achieve that or `lightbox: TRUE` is inevitably active for all the document.

Thanks in advance !

**Comment by juba** [comment]
Hi,

I just pushed an update to the development version to allow to disable the lightbox effect on a particular image by adding a "no-lightbox" class to it. I think this would only work when inserting the image directly in HTML with something like : 

```html
<img src="image.png" class="no-lightbox" />
```

So it may not suit all your needs unfortunately.

**Comment by Lucius-Cesar** [comment]
Thanks a lot ! It's really what I needed.
