### ISSUE TITLE
Robobook datatable margin

### ISSUE THREAD

**Issue by Lucius-Cesar** [juba/rmdformats#104]
Hello, I recently update the package and I noticed that there is now an important margin from either side of the datatable with Robobook template. This margin impacts also the responsivness  and I don't find the way to remove it.

I precise that I use a custom CSS to meet certain needs. So I could uderstand if robobook is not designed for such large datatables.

Here is a screen of my datatable before update
![Screenshot from 2021-04-20 12-32-43](https://user-images.githubusercontent.com/74735526/115383886-a51ac380-a1d6-11eb-82c6-ecf74144e911.png)

Here is a screen of my datatable after update
![Screenshot from 2021-04-20 12-32-25](https://user-images.githubusercontent.com/74735526/115383910-aba93b00-a1d6-11eb-905c-08fe4b12279e.png)

**Comment by juba** [comment]
Urf, you're absolutely right, the vertical position of the table was wrong. I think it should be fixed in the development version, let me know if it's still there.

Thanks for taking the time to report the issue !

**Comment by Lucius-Cesar** [comment]
Thanks a lot, it solves the problem with large datatables.
But smaller datatables are left aligned.  I noticed also that it adds also an extra space between table and filters. 

So maybe the css above could be more adaptated:

```
.book .book-body .page-inner section.normal .dataTables_wrapper .table-wrapper .no-footer{
    margin-top: 3em;
    margin-left: auto;
    margin-right:auto;
}
```

**Comment by Lucius-Cesar** [comment]
Just noticed now also that the superior border of the table is now a grey thick line instead of black thin line, it's not a problem but it is just for information.

**Comment by juba** [comment]
Yes, you're right. I reverted back to a 1px solid black line (don't really know which one is better). I also tweaked the margins below the table a bit.
