### ISSUE TITLE
Font sizes in robobook theme

### ISSUE THREAD

**Issue by lmsimp** [juba/rmdformats#106]
Hello, I am new to using `rmdformats` and I am trying to make a pretty document using the `robobook` format. I am hvaing issues changing the font size in all elements of the document. I would usually add css after the preamble as per the below example but this does not change the font size anywhere in the document. How can I change the font sizes please?

```
---
title: Test the robobook
author: "Lisa Breckels"
date: "15/04/2021"
output:
  rmdformats::robobook:
    theme: default
    fig_caption: true
    use_bookdown: true
---

<style>
body, h1 {
  font-size: 15px;
}

body, h2, h3, h4 {
  font-size: 14px;
}

body, td {
   font-size: 16px;
}
code.r{
  font-size: 6px;
}
pre {
  font-size: 10px
}
</style>

# h1 font size should be 14
Body text should be 16px

#```{r cars}
## ================= code should be 9px =========
#summary(cars)
#```
## subsection

# another h1 section header

```

**Comment by lmsimp** [comment]
![image](https://user-images.githubusercontent.com/1698853/117303676-e1a41b80-ae74-11eb-8d32-53ef8c54904d.png)

**Comment by juba** [comment]
Hi,

Yes, due to the structure of the original CSS, for your CSS to be applied you have to add some classes as element prefix. Something like this : 

```html
<style>
.book .book-body .page-inner section.normal h1 {
  font-size: 15px;
}

.book .book-body .page-inner section.normal h2, 
.book .book-body .page-inner section.normal h3, 
.book .book-body .page-inner section.normal h4 {
  font-size: 14px;
}

.book .book-body .page-inner section.normal table  td {
   font-size: 16px;
}
.book .book-body .page-inner section.normal pre>code.r {
  font-size: 6px;
}
.book .book-body .page-inner section.normal pre {
  font-size: 10px
}
</style>
```

**Comment by lmsimp** [comment]
Brilliant! Thanks so much for replying so quickly! Whilst you're online do you mind me asking on this issue if it also possible to customise the left toc header to be different from the document header? e.g. say I'd like the toc header title to be called "test" and instead of "test the robobook"

**Comment by juba** [comment]
There is no way to do it directly with `rmdformats`, but you can use a hack in JavaScript or in CSS with something like this : 

```html
<style>
<style>
ul li.title {
  visibility: hidden;
}
ul li.title:before {
  visibility: visible;
  content: "Test";
}
</style>
```
