### ISSUE TITLE
Best practices for extending a theme

### ISSUE THREAD

**Issue by fredcallaway** [juba/rmdformats#107]
I really like the robodown theme, but would like to further customize the html. Is there a good way to do this that will ensure my changes aren't overwritten by a future update?

**Comment by juba** [comment]
Well, I think the simplest way would be to use a custom CSS. If you need more customization which would need to modify the HTML template, you could either fork this repository or create your own package by reusing part of its code.

**Comment by fredcallaway** [comment]
Yeah I want to enable hypothes.is commenting which requires adding a <script> import. Forking sounds like the right call. Thanks!

**Comment by juba** [comment]
If you want to add a `<script>` in a document, you can do it directly in its body (but then you'll have to do it for each new document), or use includes to add HTML fragments : 

https://bookdown.org/yihui/rmarkdown/html-document.html#includes

This could be quite simpler than forking this project.

**Comment by fredcallaway** [comment]
Ah this is perfect, and indeed much easier. Many thanks!
