### ISSUE TITLE
Add rstudio's code_folding: hide

### ISSUE THREAD

**Issue by RCura** [juba/rmdformats#11]
Would be very usefulo to have `code_folding` as a generic argument ([like here](http://blog.rstudio.org/2016/03/21/rmarkdown-v0-9-5/)), be it with rstudio's templates or with yours.
In particular, I feel like it would really fit well with readthedown for a tutorial.

**Comment by juba** [comment]
You're right, that would definitely be useful. I'm a bit busy these days, but I think I could take a look at it next week.

Thanks for the suggestion.

**Comment by juba** [comment]
This took far too long, but the all HTML templates should now support both code folding and tabsets in the same way RStudio's HTML template does.

Thanks for the suggestion, and sorry for the delay...

**Comment by RCura** [comment]
Thanks for this enhancement :)
Just tried though, with `code_folding: hide` : I can see the `Code` button, but clicking on it does nothing.

```

> ---
> title: ""
> date: "`r Sys.Date()`"
> output:
>   rmdformats::readthedown:
>     highlight: kate
>     code_folding: hide
> ---
> 
> 
> ```{r knitr_init, echo=FALSE, cache=FALSE}
> library(knitr)
> library(rmdformats)
> 
> ## Global options
> options(max.print="75")
> opts_chunk$set(echo=FALSE,
> 	             cache=TRUE,
>                prompt=FALSE,
>                tidy=TRUE,
>                comment=NA,
>                message=FALSE,
>                warning=FALSE)
> opts_knit$set(width=75)
> ```
> 
> Test 123
> 
> ```{r blob}
> 1 + 1
> ```

```


Displays :
![capture du 2016-08-29 15-21-54](https://cloud.githubusercontent.com/assets/807703/18052745/67eb514a-6dfc-11e6-8a61-b69cdb8d9944.png)

**Comment by juba** [comment]
I think it' because there's the global `echo = FALSE` option, so R code is not generated at all. If you switch it to `TRUE` in the `knitr_init` chunk, does it work ?

**Comment by RCura** [comment]
Same problem I had in my real document : each code button appears (not only the general one with a down arrow), but clicking on these still does nothing.

**Comment by RCura** [comment]
(Note that I tried this with opening the resulting html in a browser (Chromium & Firefox), but also using an http-server to make sure it's not a "static" problem.

**Comment by juba** [comment]
An do you get the `Bootstrap's JavaScript requires JQuery` error each time ? Could you copy/paste somewhere the resulting HTML file from your first minimal example ?

**Comment by juba** [comment]
Ah, and what version of `rmarkdown` do you use ?

**Comment by RCura** [comment]
https://gist.github.com/RCura/3004f82f16d5fa3357624167185ab5ca

**Comment by juba** [comment]
Ok, it seems rmarkdown doesn't include jQuery in your file, so I added back the explicit dependency declaration in e55115892cb9f646aeca9479818a209f23997441. Does it solve the problem ?

**Comment by RCura** [comment]
Yes, working perfectly now, a big thanks ;)

**Comment by juba** [comment]
Thanks to you for your time and your feedback !
