### ISSUE TITLE
Different output from knit vs render

### ISSUE THREAD

**Issue by superboreen** [juba/rmdformats#111]
For me, the HTML output is different depending on whether I knit the document or render the document.  The knit version has the nice TOC on the left (am using downcute) but the render version does not. Also code_folding is not appearing in the render version. Is there a setting I should be using or particular syntax for the render statement.

**Comment by juba** [comment]
What command or procedure do you use to "knit" and "render" your document ?

**Comment by superboreen** [comment]
I am kitting from within RStudio. 
I have a bunch of render commands in an R file (which also creates a timestamp) and each one looks something like this:
`
rmarkdown::render(
  here::here("code","markdown1.Rmd"),
  "html_document",
  output_dir = here::here("logs"),
  output_file = paste0("markdown1_", timestamp, ".html")
)
`

**Comment by juba** [comment]
If you use `render`, I think you must replace `"html_document"` with `"rmdformats::downcute"`, otherwise Rmarkdown will just use the default HTML template.

**Comment by superboreen** [comment]
That did the trick, many thanks.  Great package by the way.
I still have a problem with code folding but I see you solved an issue with that previously so I will read that to see if it fixes my problem

**Comment by juba** [comment]
For your code folding problem, maybe try first with the development version to see if it is fixed there. Otherwise don't hesitate to open another issue.
