### ISSUE TITLE
Possible to add table caption numbering when fig_caption = true?

### ISSUE THREAD

**Issue by mvanaman** [juba/rmdformats#112]
First, these are really nice templates - thank you for this package!

It's cool that there's a `use:bookdown` option, which when `true` will allow for numbered sections and cross-references. In `bookdown::html_document2()`, we get automatic table numbering with the table captions whenever `fig_caption: true`. I see that figures are already automatically numbered, but not tables. Any chance of integrating table numbering too?

P.S. I am using the robobook theme and creating tables using the `huxtable` package, if that matters.

Thanks for your time and consideration!

**Comment by juba** [comment]
In fact table numbering is working in the same way as `bookdown` : if you use `kable()`, it will work out-of-the-box, if you use another package to generate the tables, you will have to manually add a caption with a label in a specific syntax, as explained [in the bookdown book](https://bookdown.org/yihui/bookdown/tables.html).

For `huxtable`, the following seems to be working : 

```r
tab <- hux(head(mtcars[, 1:5], 10))
set_caption(tab, "(#tab:foobar) Huxtable caption")
```
The label must be given inside `(#...)` and begin with `tab:`.

**Comment by mvanaman** [comment]
Man oh man, this seems so simple now. Thank you for your responsiveness, but sorry to bother you with a technically non-issue!

**Comment by juba** [comment]
No problem ! Thanks for taking the time to report the issue.
