### ISSUE TITLE
datable not formatting with downcute but ok with material

### ISSUE THREAD

**Issue by pgseye** [juba/rmdformats#113]
Thanks for this package - it's great for making professional looking reports in R markdown.

I've just started playing around with it and I like both the material and downcute themes but I'm having an issue getting downcute to render a datatable - it shows only one column. I'l try uploading the output as a sreengrab showing how material renders it correctly and what downcute does in comparison.

Code I used for the datatable:
```{r acs_2group_data}
acs_data_long_2ormore %>%
  DT::datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```

Any ideas?
Thanks - Paul

<img width="1130" alt="screenshot_530" src="https://user-images.githubusercontent.com/12015304/125872444-ef69678d-891f-411b-a92c-b021d842e690.png">
<img width="1040" alt="screenshot_529" src="https://user-images.githubusercontent.com/12015304/125872457-1841478a-9e8e-427a-b4a5-28fc39b3986a.png">

**Comment by juba** [comment]
Hi, just to be sure, did you try with the latest development version ?

```r
remotes::install_github("juba/rmdformats")
```

And if it still doesn't work, is there a way you could send me an extract of your data so that I can try to reproduce the problem (I tried with the same options on another dataset but it didn't trigger the issue).

Thanks for taking the time to report the issue.

**Comment by pgseye** [comment]
Hi,

Updating to the current version actually did the trick. Thank you.
