### ISSUE TITLE
Problem with dark mode

### ISSUE THREAD

**Issue by baobabprince** [juba/rmdformats#116]
I tried to use  ```download_this()``` function from ```downloadthis```` package in a with ```downcute ``` theme and the dark mode stop to work. I guess that's something about the css. Can you help me solve that?

## Reprex:

```
---
title: "Can't sleep at night"
author: "Baobab Prince"
output:
  rmdformats::downcute
---
  
### Problem

```{r}
downloadthis::download_this(iris)
```{
```
(Just remove the last `{` from the reprex)

**Comment by juba** [comment]
Hi,

And thanks for taking the time to report the issue with a reproducible example. You're right, I wasn't using the right way to update CSS variables, and this lead to a conflict with `downloadthis`. This should now be fixed in the development version.
