### ISSUE TITLE
`knitr::` in downcute skeleton

### ISSUE THREAD

**Issue by zac-garland-mc** [juba/rmdformats#117]
[downcute/.../skeleton.Rmd](https://github.com/juba/rmdformats/blob/master/inst/rmarkdown/templates/downcute/skeleton/skeleton.Rmd)

# proposed
```
## Global options
knitr::opts_chunk$set(cache = TRUE)
```

**Comment by juba** [comment]
Woops, you're right, I made some cleanups in rmarkdown skeletons but it seems I went a bit too far.

Thanks for pointing this out, it should now be fixed in all skeletons.
