### ISSUE TITLE
downcute_theme: "chaos" not working

### ISSUE THREAD

**Issue by aldanasilva** [juba/rmdformats#118]
I am trying to use downcute_theme: "chaos" but I am getting same downcute theme, not chaos.

```
output:
  rmdformats::downcute:
    downcute_theme: "chaos"
```

**Comment by juba** [comment]
Are you using the development version ?

The chaos theme is not (yet) available in the version currently on CRAN.

**Comment by aldanasilva** [comment]
I was using CRAN version, now I updated to development version and chaos theme is available there.

Thanks for your answer.
