### ISSUE TITLE
code folding commands do not work with rmdformats

### ISSUE THREAD

**Issue by megaraptor1** [juba/rmdformats#119]
I recently tried to set certain very long code chunks in RMarkdown to be hidden when the document knits but still able to be unfolded to look at the base code, following the instructions here:

https://bookdown.org/yihui/rmarkdown-cookbook/fold-show.html

However, while this did work with an html_document format, it did not work for a format in rmdformats like html_clean. Below is some code that replicates this error.

---
title: "Example"
date: "10/16/2021"
output:
  rmdformats::html_clean:
    highlight: haddock
    toc: TRUE
    toc_depth: 3
    toc_float: TRUE
    number_sections: TRUE
    thumbnails: FALSE
    code_folding: show
    df_print: paged
    DT: datatable
---
<style>
body .main-container {
        max-width: 1000px;
    }
#toc {
  width: 15%;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr);library(MASS)
knitr::opts_chunk$set(echo = TRUE,fig.width=8,fig.align="left",comment=NA)
options(width=1000)
library(tidyverse)
mammals
```

```{r class.source = 'fold-hide'}
ggplot(mammals,aes(x=log(body),y=log(brain)))+
  geom_point(shape=21,fill="gray")+
  labs(x="Log Body Size",y="Log Brain Size")+
  theme_classic()
```

The code, when run, should hide the code for the `ggplot` call in the second chunk, but allow it to be unfolded when pressing the "code" button (i.e., instead of all chunks being visible, select chunks are loaded as collapsed). This works for html_document but it does not seem to work with rmdformats.

I was wondering if there was any way to make this work for rmdformats?

**Comment by megaraptor1** [comment]
> If you want code chunks to be hidden at load time, you have to specify `code_folding: hide` instead of `code_folding: show`.

What I mean is I am trying to get all code chunks to be shown after knitting, aside from a few chunks that are very long and I want to hide for legibility. Normally what happens is it should be possible to set `cold_folding:show` for the entire document, and then add `class.source = 'fold-hide'` to specific chunks in which the code should initially be set as collapsed.

This modified code should better show what I mean. The code should produce two ggplots. The first one should have the code used to produce it shown, whereas the latter should have the code hidden in a collapsed section. This words for html_document formats, but not rmdformats.

---
title: "Example"
date: "10/16/2021"
output:
  rmdformats::html_clean:
    highlight: haddock
    toc: TRUE
    toc_depth: 3
    toc_float: TRUE
    number_sections: TRUE
    thumbnails: FALSE
    code_folding: show
    df_print: paged
    DT: datatable
---
<style>
body .main-container {
        max-width: 1000px;
    }
#toc {
  width: 15%;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr);library(MASS)
knitr::opts_chunk$set(echo = TRUE,fig.width=8,fig.align="left",comment=NA)
options(width=1000)
library(tidyverse)
mammals
```

```{r}
ggplot(mammals,aes(x=log(body),y=log(brain)))+
  geom_point(shape=21,fill="gray")+
  labs(x="Log Body Size",y="Log Brain Size")+
  theme_classic()
```

```{r class.source = 'fold-hide'}
ggplot(mammals,aes(x=log(body),y=log(brain)))+
  geom_point(shape=21,fill="gray")+
  labs(x="Log Body Size",y="Log Brain Size")+
  theme_classic()
```

**Comment by juba** [comment]
Ah, my bad, I read your issue to fast and didn't understand correctly what you were trying to do.

Some JavaScript code was indeed outdated, the problem should be fixed now in the development version.

Thanks for taking the time to report the issue !
