### ISSUE TITLE
Change theme colour 

### ISSUE THREAD

**Issue by JannahS** [juba/rmdformats#121]
Hi, 

I really love the material theme as I can split contents into different pages. However, I would like to change the theme colour and reduce the space between headers in the 'table of contents' as they seem too far apart.

Is there a way to do so?

Thanks in advance

**Comment by juba** [comment]
Hi,

This is possible if you know a bit of CSS. You can provide styles directly in your document or in an external custom CSS file which can override the template styles.

https://bookdown.org/yihui/rmarkdown/html-document.html#custom-css

Hope this helps !
