### ISSUE TITLE
Images are rendered very small by `rmarkdown::render()`

### ISSUE THREAD

**Issue by bersbersbers** [juba/rmdformats#123]
`Bug.Rmd`:

    ---
    title: rmarkdown::render("bug.Rmd")
    output:
      rmdformats::material:
        thumbnails: false
        gallery: false
        lightbox: false
        mathjax: NULL
    ---
    
    ## rmarkdown::render("bug.Rmd")
    
    ```{r}
    tmp <- tempfile(fileext = ".png")
    download.file("https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png", tmp)
    knitr::include_graphics(tmp)
    ```

In R:
```r
devtools::install_github("juba/rmdformats")
rmarkdown::render("bug.Rmd")
```

```
/usr/bin/pandoc +RTS -K512m -RTS bug.knit.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output bug.html --lua-filter /data2/bers/opt/R/4.1/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /data2/bers/opt/R/4.1/library/rmarkdown/rmarkdown/lua/latex-div.lua --self-contained --variable 'material:true' --variable 'gallery:false' --variable 'cards:true' --variable bs3=TRUE --standalone --section-divs --table-of-contents --toc-depth 1 --template /data2/bers/opt/R/4.1/library/rmdformats/templates/material/material.html --highlight-style kate --variable theme=bootstrap --include-in-header /tmp/Rtmpf9pyGi/rmarkdown-str72f64bacfcb.html 
```

In the browser:
![image](https://user-images.githubusercontent.com/12128514/141986169-280470aa-579a-43fd-a08c-f08eba446f51.png)

![image](https://user-images.githubusercontent.com/12128514/141986310-35f2c8dc-b637-4918-b0fe-d64ff6a3f3f2.png)

Is this the intended output?

**Comment by juba** [comment]
Do you have the same behavior when replacing : 

    ## rmarkdown::render("bug.Rmd")

With : 

    # rmarkdown::render("bug.Rmd")

When using `material` you should at least have one `h1` title.

**Comment by yannickberker** [comment]
@juba yes, same issue.

**Comment by bersbersbers** [comment]
@juba yes, same issue.

**Comment by juba** [comment]
Hmm, the output image size should depend on the `dpi` value of either `include_graphics` or the chunk options. Do you see a difference if you use : 

```{r dpi=50}
tmp <- tempfile(fileext = ".png")
download.file("https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png", tmp)
knitr::include_graphics(tmp)
```

(note that you could also directly include the image in markdown, but I guess you already know that)

**Comment by bersbersbers** [comment]
Yes, that's the solution - thanks! `rmarkdown::render()` is so much faster than `devtools::build_vignettes()`, so for a quick preview, it's great the same result, visually.

Just out of curiosity - how did you get to dpi 50? Does that value have any special meaning? Or did you just try a random values and then extrapolate to the original image sizes? In another document, I have to use 96 to match the size of `devtools::build_vignettes()`.

**Comment by juba** [comment]
Ah no sorry, the 50 value was just at random. According to `knitr` documentation, I think the default value should be 72 ?

**Comment by bersbersbers** [comment]
Interesting! 50 definitely gave me the correct size in the above `bug.Rmd`, but maybe that example is not sensitive to that because the image is small. My real document has a a few-thousand-pixels-wide images, so correct size is more important ;)

It has to be 96 for me, though - I tried other values, and all extrapolations hinted at 96. That value is not too random, though - this one quotes 96 for `rmarkdown`:
http://zevross.com/blog/2017/06/19/tips-and-tricks-for-working-with-images-and-figures-in-r-markdown-documents/
