### ISSUE TITLE
Adjusting the with of the content area in robobook

### ISSUE THREAD

**Issue by statquant** [juba/rmdformats#125]
Hello @juba,
Thanks for rmdformats, it's been really useful to me.
The following is not an issue but rather a question,  I understand this can be out of scope, please close if that's the case (and apologies).
I would like to use the robobook template, mainly because of the possibility to make the TOC bar disappear/appear by clicking on it.
However the width of the "content-area" is too small to my taste. I've tried to modify it follwing your advices in another issue by creating `robobook_styles.css`
```
#content {                          
    max-width: 1500px !important;   
    margin-left: -670px !important; 
    margin-right: -670px !important;
}                                   
#table-of-contents {                
    width: 500px !important;        
}   
```                                
it is working at a given "scale" (understand at say scale 80% on chrome), note I tried to replace the `px` by `%` as well with the same result.
![image](https://user-images.githubusercontent.com/3612473/145585472-5f243990-393f-43b7-93ee-74ebbb01850d.png)

**BUT**

- it does not when I rescale the zoom of my browser

![image](https://user-images.githubusercontent.com/3612473/145586180-7039491e-1d26-497a-b5b8-1a861df9ef69.png)

- further more I'd like the left margin to "persist" when the TOC is hidden (basically showing/hiding the TOC would trigger a translation of the text) but it does not seem to work like this

![image](https://user-images.githubusercontent.com/3612473/145586241-e8b8c1e9-8641-4802-a0e2-72b5de332b48.png)

Would you be able to help on the above 2 issues (or giving me pointers/letting me know if it is likely too involved)

Many thanks

**Comment by juba** [comment]
You may try something like this instead : 

```css
.book .book-body .page-inner {
    max-width: 1500px;
}
```
