### ISSUE TITLE
Possible unused lightbox dependency footprint included in readthedown when lightbox = false

### ISSUE THREAD

**Issue by sciatro** [juba/rmdformats#128]
When using `rmdformats::readthedown` with:

```yaml
    lightbox: false
    thumbnails: false
```

I see the the js / css for `magnific-popup` in the `<head`> of my final knitted html, e.g. with `self_contained: false`: 

```html
        <link href="libs/magnific-popup-1.1.0/magnific-popup.css" rel="stylesheet" />
        <script src="libs/magnific-popup-1.1.0/jquery.magnific-popup.min.js"></script>
```

After a little bit of time poking around in the final knitted page with browser dev tools I am not seeing obvious examples of either in use. On the other end when I manually remove them the overall effect of the final page appears preserved. 

My front end knowledge is minimal at best so all of this is wholly theory-free poking around but, is it possible that these dependencies are included on accident even when lightbox is false?

**Comment by juba** [comment]
Indeed, you're right, the magnific popup dependency was added systematically. This should now be fixed in the development version, magnific popup should not be included anymore if `lightbox: false`.

Thanks !

**Comment by sciatro** [comment]
Thank you for looking into it and all of the hard work on this package.
