### ISSUE TITLE
Empty JS document ready function at end of knitted <body>

### ISSUE THREAD

**Issue by sciatro** [juba/rmdformats#129]
I think I've found another quirk which is similar in concept to #128. 

When using `rmdformats::readthedown` with `lightbox: false` the final knitted HTML includes this empty  document ready function:

```html

...

  <script>
    $(document).ready(function () {

			
 		
	    });
  </script>



    <!-- dynamically load mathjax for compatibility with self-contained -->
...
```

This seems to be a result of a particular path through the conditional template logic the starts on [line 415 in template.html](https://github.com/juba/rmdformats/blob/2f96d66d5c17e421876708b3bbd2006cba624849/inst/templates/template.html#L415)

**Comment by juba** [comment]
Yes, this is not easily avoidable : the JavaScript callback is not empty if `thumbnail` or `lightbox` is not false. Not including the `<script>` tag at all when it is empty would lead to a more complex pandoc template, so I'll let it as it is as it doesn't lead to any performance or file size problem.
