### ISSUE TITLE
Compatibility with Rmd-websites

### ISSUE THREAD

**Issue by jemus42** [juba/rmdformats#13]
I was playing around with the [Rmarkdown websites](http://rmarkdown.rstudio.com/rmarkdown_websites.html) format, and I was hoping to use `readthedown` as a page layout, but unfortunately this goes wrong in all sorts of ways.

Of course I didn't expect this to work out of the box, but I think it would be a very nice addition.  

My simple experimental site can be viewed [here](http://stats.jemu.name/qm/experiments/rmd-web/_site/)

**Comment by juba** [comment]
Closing it, as I don't plan to make `readthedown` compatible with Rmarkdown websites for now...

Don't hesitate to reopen if needed.
