### ISSUE TITLE
adding a hyperlink to an image

### ISSUE THREAD

**Issue by awojtas-r** [juba/rmdformats#132]
Hi,
I'm using downcute theme which btw is great but I'm struggling with adding a hyperlink to an image because default behavior is a gallery. Is it any possibility to have a picture with title underneath and after hoovering a mouse over a picture and clicking, the default behavior would be to open hyperlink?

I'm trying to do it with 

`[![Image name](image.png)](http://www.abc.com) `

example but didn't work. It works in custom html Rmd file

Thanks
Adam

**Comment by juba** [comment]
Hi, did you try to disable lightbox by adding the following in your preamble ?

```yaml
thumbnails: false
lightbox: false
```

**Comment by awojtas-r** [comment]
Yes I did, then the picture is a bit deformed and I'm loosing a title (linking works)

**Comment by juba** [comment]
I'm not sure what you're trying to do is possible with knitr/rmarkdown. Even with the standard `html_document()` template, it seems you can either have an image with a link :

```md
[![Image name](image.png)](http://www.abc.com)
```

Or an image with a caption :

```md
[Image name](image.png)
```

But not both...

**Comment by awojtas-r** [comment]
Ok understand, thank you for taking a look into it. 
Best regards!
