### ISSUE TITLE
Tibble not Rendering when using downcute_chaos theme.

### ISSUE THREAD

**Issue by IshmaelRoslan** [juba/rmdformats#133]
Hi There,
Thanks for an awesome package for styling Rmarkdowns. I am having a problem when using the downcute_chaos theme, where my tibble outputs are not formatted as  html tables, whereas the rest of the theme works really well.
I attach a screenshot in addition to  links to the rendered page and repo containing the markdown.
I am probably doing something wrong, but can't for the life of me work out what.
Thanks for your help!
Ishmael
![image](https://user-images.githubusercontent.com/63668025/162412852-35b67f6a-8507-42d7-9234-f1e495108267.png)

[Rendered Web Page](https://ishmaelroslan.github.io/DDP/)
[Code](https://github.com/IshmaelRoslan/DDP/blob/main/index.Rmd)

**Comment by juba** [comment]
Did you try modifying the `df_print` preamble option, as described below ?

https://bookdown.org/yihui/rmarkdown/html-document.html#data-frame-printing

**Comment by IshmaelRoslan** [comment]
I hadn't but I have just tried as follows in the yaml header and tried all of the different options. paged, tibble, kable, etc...
Unfortunately it still renders as a code printout of a tibble, no matter what I change.
---
title: "Interesting Country Names"
author: "Ishmael Roslan"
date: "`r Sys.Date()`"
output:
        rmdformats::downcute:
                downcute_theme: chaos
                df_print: paged
---

**Comment by IshmaelRoslan** [comment]
I have  just solved the problem: I removed `cache = TRUE` from the knitr chunk.
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, cache = TRUE,
                      message = FALSE, echo = TRUE)
```
Thanks for your help anyway!

**Comment by juba** [comment]
Ah, glad you solved it !
