### ISSUE TITLE
readthedown theme : table of content hightlight

### ISSUE THREAD

**Issue by Lipinski-B** [juba/rmdformats#134]
Hi,

I don't understand why I have this result in the table of content part when I use this following code : 
```
---
title: "Projet"
author: "Me"
date: '2022-04-01'
output:
  rmdformats::readthedown
---

# test
## test1
## test2
```

![Capture d’écran de 2022-04-12 14-12-39](https://user-images.githubusercontent.com/62985059/162960003-94cf9da2-5869-4231-928a-3a28cf3cea66.png)

It seems different compare to what I should have.
Any idea?

Cheers,
Boris

**Comment by juba** [comment]
Hi,

It's a bit strange, I don't get the same result here : 

![image](https://user-images.githubusercontent.com/245367/162960468-c2294a28-d554-4cf9-bfd5-81013bbb284a.png)

Do you get the same result even with some content between your headings ?

**Comment by Lipinski-B** [comment]
Yeah, no matter what are written inside my script, I finally have the same result :(

**Comment by juba** [comment]
Could you please try to send me the generated html file ?

Did you try with rmdformats development version ?

**Comment by Lipinski-B** [comment]
[tt.html.gz](https://github.com/juba/rmdformats/files/8472826/tt.html.gz)

Ahhhh yes! I had the development version get by :

```
install.packages(remotes)  # if necessary
remotes::install_github("juba/rmdformats") 
```

Now I downgrade the package by : 

```
install.packages("rmdformats", force=T)
```

And everything looks so much more pretty!!!!!!!!

Many thanks, maybe it has to do with an option currently in modification in your development version.

**Comment by juba** [comment]
That's very strange, there was indeed a bug in the development version on Github, but on my development version locally...

Anyway, I think it should be fixed now, so even if you reinstall the development version, `readthedown` TOC should display correctly.

Thanks for taking the time to report the issue !
