### ISSUE TITLE
Release to CRAN

### ISSUE THREAD

**Issue by bersbersbers** [juba/rmdformats#136]
Congratulations on closing all issues :) Sorry for opening another one, but would you agree it's a good time to release this to CRAN? I'd love to see the fix to https://github.com/juba/rmdformats/issues/122 there. Thanks, and good luck ;)

**Comment by juba** [comment]
Ah yes, good idea, it's been a while since the last release. I'm looking into it, thanks for the suggestion.

**Comment by juba** [comment]
rmdformats 1.0.4 is on its way to CRAN. Should be available in the following hours / days.

Thanks !

**Comment by bersbersbers** [comment]
Thanks to you :)
