### ISSUE TITLE
company/university name for title 

### ISSUE THREAD

**Issue by Bolin-Wu** [juba/rmdformats#137]
Hi!

First of all, thank you for creating/maintaining such wonderful RMD formats. I use this template a lot during my work. However, I wonder that is it possible to add a company/university name in the YAML preamble, in addition to "title", "author" and "date"?

I tried to find if there is such closed issue but I can not find any. Thank you for your time regarding my question!

Best,
Bolin

**Comment by juba** [comment]
Hi, do you use a specific template ?

There is an `affiliation` field, which is a child of the `author` field that can be used for things like these. But I'm not sure it will be rendered well in the different `rmdformats` templates.

You can use with something like : 

```
---
author:
  - first_name: "zzz"
    last_name: "zzz"
    affiliation: "zzz"
---
```

If it is not rendered nicely you can also add it to the `subtitle`, `author` or `date` field by inserting a line break manually with `<br>`, I think it should work.

Let me know if you manage to get something suitable with the template you're using...

**Comment by Bolin-Wu** [comment]
> 

Hi, Thank you for reply!

I am using downcute.

I ran:

`
title: "Template Title"
author:
  - first_name: "Bolin"
    last_name: "Wu"
    affiliation: "Test"
date: 'YYYY-MM-DD (updated: `r Sys.Date()`) '
`

But it renders:


![image](https://user-images.githubusercontent.com/55343566/169263273-ad97fb09-8f0f-4e3c-b266-0ec500e153d3.png)

It seems that the affliation does not work or am I missing anything?

Best,
Bolin

**Comment by juba** [comment]
Ah, sorry, in fact it is supported in `downcute` but you have to just give a `name` subfield of `author` :

```
---
author:
  - name: "zzz"
    affiliation: "zzz"
---
```

But it only appends affiliation behind the author name, so I'm not sure it is really interesting...

**Comment by Bolin-Wu** [comment]
> Ah, sorry, in fact it is supported in `downcute` but you have to just give a `name` subfield of `author` :
> 
> ```
> ---
> author:
>   - name: "zzz"
>     affiliation: "zzz"
> ---
> ```
> 
> But it only appends affiliation behind the author name, so I'm not sure it is really interesting...



> Ah, sorry, in fact it is supported in `downcute` but you have to just give a `name` subfield of `author` :
> 
> ```
> ---
> author:
>   - name: "zzz"
>     affiliation: "zzz"
> ---
> ```
> 
> But it only appends affiliation behind the author name, so I'm not sure it is really interesting...

I see, I though it would give a newline + little nice icon like "name" and "date" but thank you very mcuh for your time!

**Comment by juba** [comment]
I just commited a small change in the development version of `rmdformats` to do just that : separate name, affiliation and email with newlines and icons.

If you want to test it and give any feedback, don't hesitate to do so !
