### ISSUE TITLE
Add header page splits to robobook?

### ISSUE THREAD

**Issue by thomasbparr** [juba/rmdformats#138]
What I really want to ask is: Can you add toc_depth to 'material', but given your previous responses I know that that is a non-starter. Instead, would it be possible to add the split pages by header level functionality to robobook?

**Comment by juba** [comment]
You mean the same "cards" functionality as in `material` ? Unfortunately no, this would be a major overhaul of the template. `material` was designed from the ground up (not by me) for this feature, I think.
