### ISSUE TITLE
Check and install package `ProjectTemplate` in your rmarkdown skeleton files?

### ISSUE THREAD

**Issue by haozhu233** [juba/rmdformats#14]
Hello, when I was trying to organize some rmd templates on CRAN, I came across this package. I like the theme included in this package. Good job!

Also, for all the `projecttemplate` templates, do you want to write a check & install step for package ProjectTemplate? This package is not declared in the DESCRIPTION (and I also see why you didn't). For people without that package, it will throw an error message on their first attempt.

**Comment by juba** [comment]
Hi, and sorry for my very late answer.

Thanks for your feedback, I'm glad you find this package useful. Concerning your request, after a bit of thinking I don't think I'll implement it, for several reasons : 

- I guess that people who would use the `ProjectTemplate` skeletons know about the package, so would know what to do when they get the error message.

- I don't really like the idea to install a missing package without asking for the user first, and that would lead to too much code to be included in every document.

- If we don't install the package, just throwing a warning would not be really more useful than the R error message.

So I think that I'll let this as it is. But feel free to argue if you disagree :)

**Comment by haozhu233** [comment]
Haha, never mind. I was in an illusion that we can automatically generate something like `ggplot2-exts` without too much editing efforts for r markdown. I'm glad you closed this issue. I should have closed it earlier by myself. ;)
