### ISSUE TITLE
Is it possible to add a small blank box when class.source = 'fold-hide' is called in html_clean to show where code blocks are present?

### ISSUE THREAD

**Issue by megaraptor1** [juba/rmdformats#142]
This is more of a quality-of-life feature request than a specific bug, but it's something that has been a slight issue and I could not find anywhere to submit feature requests for `rmdformats` so I thought I would submit it here.

I have been greatly enjoying using rmdformats in my work, though I've been running into a minor issue that makes using code difficult. Specifically, I have a very long markdown document, so I have been using the `class.source = 'fold-hide'` a lot to hide very long stretches of code to make my knitted document more legible. I have been using the rmdformat html_clean in this case.

However, I have been running into a problem. Specifically, the hidden code button is very small and it is often hard to see if the code is present. I was wondering if there was any way to add an option for a small empty box to remain when the code is folded to show there is code present? The issue I am running into is when I have a lot of code blocks in a row without body text in the knitted document to break them up it can be confusing to find the button to unfold the code, and it can get overlooked among all the kables and ggplots. I understand it's supposed to be out of the way and it usually is, it's just in some cases it can get so out of the way it makes the code hard to find. I've seen this done in other formats but I didn't know if it was possible here. If not, no problem, but I just wanted to ask.

Here's what it looks like now...

![What it looks like now](https://user-images.githubusercontent.com/74024763/181019867-1a3b8729-b147-46da-8520-918def95917a.jpg)

And here's what I mean.

![What I mean](https://user-images.githubusercontent.com/74024763/181019909-297b4471-d339-4b8d-bc8b-b67ba8acf73f.jpg)

**Comment by juba** [comment]
I don't really see a way to achieve precisely what you describe, but maybe you could change the size of the code folding buttons if you find them too small. The following code in the beginning of your document should increase their font size.

```html
<style>
.code-folding-btn {
  font-size: 15px;
}
</style>
```

**Comment by megaraptor1** [comment]
If I found some code elsewhere that did something similar (html and I think probably latex, but maybe not RMarkdown), would that help? I've seen html pages that do something similar, but don't know how to extract the code.

**Comment by juba** [comment]
Not really unfortunately, the problem is that the code source is already styled, plus there is some JavaScript to manage folding / unfolding, so preexisting CSS rules would not necessarily apply correctly.
