### ISSUE TITLE
how to change the default color 

### ISSUE THREAD

**Issue by djhbs** [juba/rmdformats#143]
Thanks for this wonderful formats

There is a need to change the default color, for example the tittle of contents and sidebar color when using the template 
https://github.com/juba/rmdformats/blob/6f4310540eb2e21d3d2e6445d78a62a469720251/R/readthedown.R#L83
For now, I try to edit the **readthedown.css** manually, it worked,
I wonder if there is a more convenient way to do it.
Thank you very much.

**Comment by juba** [comment]
Hi, there is indeed no built-in way to do it easily besides of creating a custom CSS. The following issues may help :

- #37 
- #86

**Comment by djhbs** [comment]
adding a custom it is a better way, thank you very much for you time and feedback
