### ISSUE TITLE
Using lightbox for images within a DT datatable

### ISSUE THREAD

**Issue by sam-israel** [juba/rmdformats#146]
Hi,

I am displaying images within a DT datatable. I want clicking on the images from within the table (in order to enlarge them) to be possible. 

However, I have found that this works only for the first "page" of the data table.  In the attached file, the maximum length of items to be displayed per table page is 4 (meaning that there are only 4 items displayed simultaneously). And - only the first four images in the table are able be clicked, and enlarged. It does not work for the other images in the data table.
[sample.zip](https://github.com/juba/rmdformats/files/10336358/sample.zip)

Is there a way for me to fix that?

**Comment by juba** [comment]
Hi,

Lightbox is initialized at load time, more precisely every image in the document is assigned a `image-lb` class after the page is loaded. The problem is that images displayed via `DT` pagination are not present at load time so they are not initialized correctly. 

The only possible workarounds I can think of would be either to assign the `image-lb` class to all images via `DT` (but this may not be possible), or add custom JavaScript code to add the class dynamically by listening to a `DT` event when using pagination (but it may be complicated to implement).

**Comment by sam-israel** [comment]
I think that I did manage to assign the image-lb class to all images via DT (passing a javascript function to DT).

It is now possible to click on all images. However, now, when I actually click on them the message "The image could not be loaded" is displayed. 
[sample_addClass.zip](https://github.com/juba/rmdformats/files/10337884/sample_addClass.zip)

Are you able to help or suggest a direction?

**Comment by juba** [comment]
I think the problem comes from the fact that you put a `image-lb` class to your `<td>` elements instead of `<img>` tags.

**Comment by sam-israel** [comment]
Thanks for the tip. 

I solved the problem, simply by manually adding `class="image-lb" ` to the URI of the image created (which is later passed to datatable).

```
---
output:
  rmdformats::robobook:
    gallery: false
    lightbox: true
    self_contained: true
    thumbnails: true
---
```{r}
library(DT)

# Reading files, and converting to URIs
files <- list.files("samplePlots/", pattern = paste0("\\.", "(png|jpg|gif)", "$"), full.names = T)
img_uris <- paste0("<img src=\"", sapply(files, knitr::image_uri), "\"/ ", ' class="image-lb"' , ">")

#Creating a data frame with images and their names , and displaying it as a data table
df <- data.frame(image = img_uris, title = files)

DT::datatable(df, escape = FALSE, rownames = F, colnames = c("", ""), options = list(pageLength = 4, lengthChange = FALSE, ordering = FALSE, autoWidth = TRUE, columnDefs = list(list(width = "10%", targets = c(-1)) ) )   )
```
