### ISSUE TITLE
page-resizing

### ISSUE THREAD

**Issue by kkmll** [juba/rmdformats#147]
Dear developer, when I the generate a report by using one of these templates (I tried readthedown in html format) and view it on a web-browser, there is a lot of white space on the right site of the page. Which line(s) of the css template should I modify to make it cover all of the page? thanks..

**Comment by juba** [comment]
This should be possible by adding the following to your document or to a custom CSS file :

```html
<style>
#content {
    max-width: none;
}
</style>
```

**Comment by kkmll** [comment]
thanks.. :)
