### ISSUE TITLE
Utilizing templates for quarto

### ISSUE THREAD

**Issue by xinzhuohkust** [juba/rmdformats#149]
Hi, I was wondering if the templates could be used for quarto html file? Thanks.

**Comment by juba** [comment]
No, this is not possible as far as I know. Quarto has developped a specific extension API which allows to develop custom formats, but `rmdformats` templates would have to be ported to this new API. 

I may take a look into it at some point but can not guarantee it.

**Comment by juba** [comment]
FYI, I created a quarto format which is a porting of `robobook`. It is available here:

https://github.com/juba/bookup-html

I'll work on other templates in the next months.
