### ISSUE TITLE
Add some demo contents to your templates?

### ISSUE THREAD

**Issue by haozhu233** [juba/rmdformats#15]
Hello, as I said in the last issue, I like the styles of this package. I'm also wondering if you can add some functionality demonstration contents to those skeleton files (like what they have done in the [rstudio/tufte](https://github.com/rstudio/tufte/blob/master/inst/rmarkdown/templates/tufte_html/skeleton/skeleton.Rmd) package)?

**Comment by juba** [comment]
I'm not a big fan of adding demo content in skeleton files. This could be useful the first time you use the template, but I find it a bit cumbersome to have to delete all the content each time you create a new document...

Maybe the sample documents in the `resources/examples` directory and the vignette could be more detailed and expanded a bit ?
