### ISSUE TITLE
Template readthedown rmdformats title duplicate 

### ISSUE THREAD

**Issue by Cris57420** [juba/rmdformats#151]
Bonjour

je suis à la recherche d’une façon de supprimer la duplication du titre lorsque l’on utilise le format rmdformats readthedown. J’aimerai en d’autres termes mettre un logo dans le sidebar en haut à gauche et un vrai titre en texte sur le haut de la page. Jusque là mes recherches sont vaines

merci vraiment pour votre aide

bien cordialement

cris

**Comment by juba** [comment]
Bonjour,

Pour faire quelque chose dans le style il faut que vous ajoutiez des règles CSS custom, soit depuis un fichier externe soit en ajoutant directement dans votre document quelque chose comme : 

```html
<style>
#sidebar h2 {
    background: url("Logo.png");
    height: 100px;
}

#sidebar h2 a {
    visibility: hidden;
}
</style>
```
