### ISSUE TITLE
Change font style (size, color, family) using downcute template

### ISSUE THREAD

**Issue by chedgala** [juba/rmdformats#152]
I'm using the downcute template, but the font sizes look too big for me. I have tried so hard to change the font size (CSS file), however nothing has worked.

Curiously, CSS file changes work for the readthedown template.

This is my sample code

![image](https://user-images.githubusercontent.com/8940694/222553846-d3103843-c009-4fd5-9bcf-b0c51cb86ebf.png)

Which produces this!

![image](https://user-images.githubusercontent.com/8940694/222558688-51ccf08f-4f72-42df-8819-b1dc8a5e13ad.png)

Please help.

**Comment by juba** [comment]
Hi,

Well it depends on what element you want to modify, but something like this should work : 

```html
<style>
/* Main title */
h1.title {
  font-size: 1.5em;
}
/* H1 heading */
.page-content h1 {
  font-size: 2em;
}
/* H2 heading */
.page-content h2 {
  font-size: 1.8em;
}
/* Global font size */
body {
  font-size: 12px;
}
</style>
```
