### ISSUE TITLE
anyway to disable the dark mode toggle in downcute?

### ISSUE THREAD

**Issue by travis-leith** [juba/rmdformats#156]
I went with downcute because I liked the idea of a toggle. However, it turns out dark mode does not look good with the static parts of my document. But, I am very happy with the light mode rendering of downcute, and do not want to change it. Instead, I would like to hide the dark mode toggle. Is there an option for this? I did not see one in the docs.

**Comment by juba** [comment]
There is no option for this, but you could hide it with a bit of CSS, something like:

```css
.dark-theme-toggler {
    display: none;
}
```

**Comment by travis-leith** [comment]
Thanks, this works.
