### ISSUE TITLE
Compatibility with embedded Shiny applications?

### ISSUE THREAD

**Issue by mike-powell** [juba/rmdformats#17]
Can I embed a Shiny app in a readthedown template html document?  I tried changing the document preamble to resemble what I typically see on an HTML document with Shiny content:

Usual Preamble Chunk-
```
output: html_document
runtime: shiny
```
Tried this for readthedown (added the runtime line)-
```
output:
  rmdformats::readthedown:
    highlight: haddock
runtime: shiny
```
I get the following error:

> Error: formal argument "extra_dependencies" matched by multiple actual arguments

Is there a fundamental incompatibility with the readthedown template and embedding Shiny content, or is there something incorrect about my attempt to enable Shiny content using this template?

**Comment by juba** [comment]
No, you're right, I've never tried to run a shiny app inside one of `rmdformats` document template, and there seems to be an incompatibility. I'll try to take a look at it.

Thanks for taking the time to report it.

**Comment by juba** [comment]
Templates should now be compatible with embedded shny apps. But I'm not sure of the layout quality for shiny apps with complex interfaces...

**Comment by mike-powell** [comment]
It works perfectly.  I don't see any issues with the layout quality of the simple apps I have tried so far.  Thanks!
