### ISSUE TITLE
[Question] How do I plug in an unevaluated header string in a loop?

### ISSUE THREAD

**Issue by happyshows** [juba/rmdformats#18]
Hi, I was trying to utilize the readthedown theme to layout my report.
However, the h1() tag, which should be equivalent to # after evaluation, was not pick up by the theme to generate tab on the TOC menu. Is there any workaround here? My minimal example below, I was expecting 'p1' 'p2' to show up on the TOC menu.

```
---
title: "Untitled"
output: 
  rmdformats::readthedown:
    self_contained: true
    highlight: tango  
---

{r message=FALSE,echo=FALSE,warning=FALSE}
library(plotly)
library(htmltools)

d <- diamonds[sample(nrow(diamonds), 1000), ]
p1 <- plot_ly(d, x = ~carat, y = ~price, mode = "markers", color = ~carat)
p2 <- plot_ly(d, x = ~price,y = ~carat,  mode = "markers", color = ~carat)
ls <- list(list(comment = 'p1',viz = p1),
           list(comment = 'p2',viz = p2)
)

b <- lapply(ls,function(obj){
  tags$div(h1(paste0('Header: ',obj$comment)),
           obj$viz,
           hr()
  )
})
htmltools::tagList(b)
```

**Comment by juba** [comment]
Hi,

Well, `rmdformats` uses  `rmarkdown` internally to generate the table of contents, and it seems that a `<h1>` header must be inside a certain section to appear in the TOC. As such, your example doesn't work in the standard `html_document` format.

Maybe a workaround could be to use inline chunks like this ?

    ```{r echo=FALSE}
    x <- "Foo"
    ```

    # Header `r x`

**Comment by happyshows** [comment]
I thought about this however my goal was to programmatically render the document. 
Is there a way to put the code you mentioned in a string and render it on the fly?
something like (pseudo code only)
params: object
template <- '
param: object
```{r echo=FALSE}
x <- object$comment
```
# Header `r x `
object$viz
'
txt <- lapply(ls,function(obj){
  template(obj)
cat('\n')
 )

rmarkdown::render('txt')

**Comment by juba** [comment]
Not sure if it is what you want to do, but you can produce markdown from your chunks, like this :

    ```{r echo=FALSE, results="asis"}
    x <- "Foo"
    cat("# ", x)
    ```

In this case the header is included in the generated table of contents...
