### ISSUE TITLE
[Question] how do I make the content in html_docco wider?

### ISSUE THREAD

**Issue by happyshows** [juba/rmdformats#19]
Currently, it only occupies <50% of my screen width, is there any place where I can specify minimal width by pixel (knowing that it's responsive)?

**Comment by juba** [comment]
Could you tell me which format you are using ?

**Comment by juba** [comment]
First, you'll have to install the latest dev version as there was a bug in margins specification which prevented to achieve this : 

```{r}
devtools::install_github("juba/rmdformats")
```

Then to change your document maximum width, add something like this to a CSS file : 

```{css}
.main-container {
  max-width: 1500px !important;
}
```

And declare this CSS file in your document preamble : 

```
---
title: "Title"
date: "`r Sys.Date()`"
output:
  rmdformats::html_docco:
    css: css_file.css
---
```

**Comment by happyshows** [comment]
thanks
