### ISSUE TITLE
pandoc: Could not determine mime type   Error

### ISSUE THREAD

**Issue by happyshows** [juba/rmdformats#20]
Hi,

The following test Rmd is causing an error in pandoc on my linux box (pandoc version 1.12   knitr 1.14 rmarkdown 1.0  rmdformats 0.3).

```
---
title: "Test Report"
output:
  rmdformats::html_docco:
    self_contained: true
---

This is a Test
```

pandoc: Could not determine mime type for `/usr/lib64/R/library/rmdformats/templates/bootstrap-3.3.6/css/../fonts/glyphicons-halflings-regular.woff2'

however, if I turned self_contained to false, pandoc renders ok, but it lose the purpose of embedding object in rmd file.

Thanks.

**Comment by happyshows** [comment]
I just ran again, this time it show up as 

pandoc: Could not determine mime type for `/usr/lib64/R/library/shiny/www/shared/bootstrap/css/../fonts/glyphicons-halflings-regular.woff2'
Stack trace (innermost first):
    51: pandoc_convert
    50: convert
    49: rmarkdown::render
    48: download$func
     1: runApp
Error : pandoc document conversion failed with error 1

I'm using rmarkdown:render to generate html via Rmd file.

**Comment by juba** [comment]
You should upgrade your pandoc or RStudio version. `woff2` fonts mime types should be supported in pandoc since about a year and a half : 

https://github.com/jgm/pandoc/commit/7031748a434c0624ca2139e91da0ea8a5559169c

**Comment by happyshows** [comment]
Confirmed closure after I switched to use pandoc 1.17, thanks for pointing out the direction.

**Comment by JiaxiangBU** [comment]
Hi @juba, I have a similar issue, and I post this question on the [Community](https://community.rstudio.com/t/get-errors-when-i-include-webp-figure-in-rmd-document/22278).

The fonts is `webp`, and I find mime already includes this one.

**Comment by juba** [comment]
`webp` seems to be a fairly recent image format, and it is not yet supported by Pandoc, as you can see here : 

https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/MIME.hs

This is really pandoc related, you should open an issue there I think...

**Comment by JiaxiangBU** [comment]
Hi @juba  thanks for your  reply, I open a [issue ](https://github.com/jgm/pandoc/issues/5267#issue-405958542)on pandoc repo now.
