### ISSUE TITLE
Change readthedown color from red to light blue

### ISSUE THREAD

**Issue by Emaasit** [juba/rmdformats#21]
Is there functioonality to change the theme color of readthedown from its current red to light blue just like in [readthedocs](http://docs.readthedocs.io/en/latest/index.html)?

**Comment by juba** [comment]
Hi,

There is no built-in way to do this, but you should be able to customize the theme appearance by using a custom CSS : 

http://rmarkdown.rstudio.com/html_document_format.html#custom_css
