### ISSUE TITLE
Add Github icon

### ISSUE THREAD

**Issue by Emaasit** [juba/rmdformats#22]
Please add functionality for a Github icon to link to the Github repository for the code just like in [readthedocs](http://osgearth.readthedocs.io/en/latest/user/spatialreference.html)

**Comment by juba** [comment]
I don't think a template would be the best place to add this feature, as it wouldn't be used by everybody.

But you should be able to add one manually, for example by adding a custom `<div>` in the content of your document, and positioning and styling with a custom CSS file.
