### ISSUE TITLE
Pandoc can't find tabsets.js

### ISSUE THREAD

**Issue by m-stanley** [juba/rmdformats#23]
Hey,

I'm having an issue with the rmdformats templates where pandoc can't find all the related files if `self_contained: yes`. `self_contained: no` stops the problem, but I want my files to be self-contained, so it's not very helpful. ~~The issue also doesn't affect my colleagues, so it's probably something I've configured incorrectly~~ (it turned out my colleague was still on rmdformats 0.2 and I had 0.3. With 0.3 or the master branch from github, it was broken for both of us, see below), but I can't work out what so I was hoping that perhaps someone here can help. This is the full error message just trying to knit the default material template:

```
  |................................                                 |  50%
   inline R code fragments

  |.................................................................| 100%
label: knitr_init (with options) 
List of 2
 $ echo : logi FALSE
 $ cache: logi FALSE



processing file: testing.rmd

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS testing.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output testing.html --smart --email-obfuscation none --self-contained --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --variable "lightbox:true" --variable "thumbnails:true" --variable "gallery:false" --standalone --section-divs --table-of-contents --toc-depth 1 --template "C:\Users\mstanley\Documents\R\win-library\3.3\rmdformats\templates\material\material.html" --highlight-style kate --variable "theme:bootstrap" --include-in-header "C:\Users\mstanley\AppData\Local\Temp\RtmpeeCmZv\rmarkdown-str1bdc103554f2.html" 
output file: testing.knit.md

pandoc.exe: Could not fetch /tabsets.js
/tabsets.js: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
In addition: Warning messages:
1: MathJax doesn't work with self_contained when not using the rmarkdown "default" template. 
2: running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS testing.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output testing.html --smart --email-obfuscation none --self-contained --mathjax --variable "mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --variable "lightbox:true" --variable "thumbnails:true" --variable "gallery:false" --standalone --section-divs --table-of-contents --toc-depth 1 --template "C:\Users\mstanley\Documents\R\win-library\3.3\rmdformats\templates\material\material.html" --highlight-style kate --variable "theme:bootstrap" --include-in-header "C:\Users\mstanley\AppData\Local\Temp\RtmpeeCmZv\rmarkdown-str1bdc103554f2.html"' had status 67 
Execution halted
```

I should add that I'm behind a proxy that requires custom Certificate Authorities to be added to the certificate store of anything that's connecting to the internet. I haven't identified where pandoc keeps its CA certs yet so when pandoc is trying to get `https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML`, it will fail. I tried explicitly setting `mathjax: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"` as an option under rmdformats::material: in the yaml header of my rmd file and that didn't solve the issue, so this might be a red herring, and the error message refers to tabsets.js anyway.

```
---
title: ""
date: "`r Sys.Date()`"
output:
  rmdformats::material:
    highlight: kate
    mathjax: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
---
```

**Comment by m-stanley** [comment]
Hey again,

So my colleague who had it working was helping me to test the changes that I made to our markdown template that I was trying to test, and I managed to break it on her machine as well :) She was running an older version of rmdformats and I had her update to the latest github version of rmdformats in the process. That broke it. Downgrading to the CRAN version then didn't solve the problem. We're trying to work out which version she had installed now.

**Comment by m-stanley** [comment]
I noticed that CRAN has version 0.3 of rmdformats but it hasn't been tagged as a release here in Github. We should be able to find it anyway but it would have been helpful if all the releases were tagged.

**Comment by m-stanley** [comment]
Downgrading to rmdformats 0.2 fixed the issue for both of us

**Comment by juba** [comment]
Hi,

First, sorry for the lack of tagging of the 0.3 version, I had forgotten to do it after the CRAN release, but it should be present now.

Unfortunately I can't reproduce the problem on my system. Would you have a sample document that would generate the error ? And, does it work with a simple `html_document` rmarkdown output ?

**Comment by juba** [comment]
Ok, finally I may have tracked the origin of the problem. Could you please try to compile your document again with the latest Github version ?

    devtools::install_github("juba/rmdformats")

**Comment by treysp** [comment]
That fixed it for me - thanks!

**Comment by m-stanley** [comment]
Yep this resolved it - thankyou!

**Comment by juba** [comment]
Good to know. Thanks for taking the time to report the problem.

**Comment by pat-s** [comment]
@juba CRAN version should be updated with that fix :)

**Comment by juba** [comment]
Yep, you're absolutely right. I've got one more fix to do, and I'll try to upload to CRAN soon.

Thanks for the reminder :)

**Comment by juba** [comment]
@pat-s Just for information, I just pushed a fixed version on CRAN.

Thanks !
