### ISSUE TITLE
Using pilltabs with standard htmldocument

### ISSUE THREAD

**Issue by dmenne** [juba/rmdformats#25]
When I try to use `pilltabs` with a standard htmldocument or bookdown, it works, but initially there is no selected tab. I do not want to use one of your special templates, because these do bad things with small inserted png images in tables, stretching to fill the column, That's probably another issue to report separately.

```
```{r}
rmdformats::pilltabs(table(iris$Species, cut(iris$Petal.Length, 3)))
```
```

**Comment by juba** [comment]
You're absolutely right, this should be fixed now in the development version : 

```
devtools::install_github("juba/rmdformats")
```

Don't hesitate to report your other problem in a separate issue.

Thanks for taking the time to report the problem.

**Comment by dmenne** [comment]
Ouff... Faster than light.
