### ISSUE TITLE
png are resized too large with html_clean

### ISSUE THREAD

**Issue by dmenne** [juba/rmdformats#26]
[b.zip](https://github.com/juba/rmdformats/files/796220/b.zip)

Small images are resized with html_clean

Looks good in readthedown

![toobig](https://cloud.githubusercontent.com/assets/506275/23255739/ff0d6e4a-f9bc-11e6-99c8-49c03d0a3ac9.png)

**Comment by juba** [comment]
Thanks for the report and the reproducible example. I think it should be fixed now.

**Comment by dmenne** [comment]
Fast and almost at target. Images are small now, row height of table is still to large. Compare with vanilla html_document.

**Comment by juba** [comment]
Sorry, I should have seen this. This may be fixed now :-)
