### ISSUE TITLE
# headers with . not behaving properly

### ISSUE THREAD

**Issue by mdlama** [juba/rmdformats#28]
In the material theme, any `<h1>` header (# in markdown) with a period in the title doesn't display.  Having a period in the title of the # headers has a different symptom in the readthedown template: Anchors don't form properly.

**Comment by juba** [comment]
Sorry for my late answer.

You're right, this is a known issue not related to the package but to pandoc. If you have dots in your headers you'll have to add ids manually : 

https://github.com/juba/rmdformats/issues/6

**Comment by mdlama** [comment]
Thank you!
