### ISSUE TITLE
Hide code in readthedown

### ISSUE THREAD

**Issue by holtzy** [juba/rmdformats#30]
I really like the readthedown template and thank the author for this nice library.
However, it looks like the option allowing to hide code by default does not work.

This piece of code works with base rmd:

    ---
    title: "test hide code"
    output:
      html_document:
        code_folding: hide
    ---
    here is some code
    ```{r }
    1+1
    ```

But the code is not hidden anymore if we use the template:

    ---
    title: "test hide code"
    output:
      rmdformats::readthedown:
        highlight: kate
      html_document:
        code_folding: hide
    ---
    
    here is some code
    
    ```{r }
    1+1
    ```

Thanks for your help!

**Comment by juba** [comment]
Well in fact it's not a bug, it is the YAML header of your file which contains an error : the `code_folding: hide` parameter is not associated with `rmdformats::readthedown` but with `html_document`. The following document works fine : 

    ---
    title: "test hide code"
    output:
      rmdformats::readthedown:
        code_folding: hide
    ---
    
    here is some code
    
    ```{r }
    1+1
    ```

**Comment by vkoul** [comment]
Hi Juba, 

I am using `SQL` queries in my chunk, the code folding option is not working for the same, although its working perfectly for `R` code chunks in the rmd file. Anyway to have the code-folding option for SQL code. 

Sample sql code:
```{sql table_creation, eval=FALSE, include=TRUE}
SELECT sub_lot
	,cal_date
FROM table 
```
