### ISSUE TITLE
Using google font from http causes Chrome warning

### ISSUE THREAD

**Issue by jflycn** [juba/rmdformats#32]
This is fine with local files, but gets warning from Chrome when I uploaded the content to the web server and access remotely. 

For example: docco.css uses http://fonts.googleapis.com/css?family=Rambla

Warning from Chrome:
Mixed Content: The page at 'https://***' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Rambla'. This request has been blocked; the content must be served over HTTPS.

**Comment by juba** [comment]
Yes, you're right, Google Webfont should be accessed over https.

This should be fixed now in the dev version. Thanks for the taking the time to report the problem, and let me know if it's still there.
