### ISSUE TITLE
Is there a way to turn off the extra js codes?

### ISSUE THREAD

**Issue by jflycn** [juba/rmdformats#33]
I have only used docco. There are extra javascript codes added after the content. One is to add class and behavior to img. Another is for MathJax. I am wondering can this be turned off? Rightnow I just manually remove them after the HTML files are generated.

Thanks!

**Comment by juba** [comment]
No, sorry, there's no way to turn off JavaScript code, as this would break presentation and/or features.

Why do you want to turn it off ?

**Comment by jflycn** [comment]
I want to control the image size and remove the CSS border.

I was wondering there might be an option in the YAML can turn it off. If
not, I may fix the image with custom CSS .

For the MathJax, should it follow the YAML option to NULL it out?

**Comment by juba** [comment]
I think the only way will be to override styling with a custom CSS. Let me know if it doesn't work.

For the `null` mathjax option, yes, you're right, it should honor it. I'll take a look at it.

**Comment by juba** [comment]
Mathjax should not be included anymore when `mathjax: null` in the YAML preamble. Thanks for taking the time to report it.
