### ISSUE TITLE
Fluid images

### ISSUE THREAD

**Issue by tyokota** [juba/rmdformats#34]
Thank you for the great templates! Is there a way to make the figures fluid - resize with the window? I am setting `fig_width: 9`, which causes the image to "bleed" off the column when the browser is resized.

**Comment by juba** [comment]
What template are you using ? `material` maybe ?

**Comment by tyokota** [comment]
Yes `material`.

**Comment by juba** [comment]
I've just added a missing `max-width` to the material CSS in the dev version. Could you please check if it solves your problem ?

Thanks for taking the time to report it !

**Comment by tyokota** [comment]
Thank you @juba. The update solved the problem.
