### ISSUE TITLE
Compatibility with cross-references?

### ISSUE THREAD

**Issue by richarddmorey** [juba/rmdformats#35]
I'm trying to compile Rmarkdown with figure cross-references (e.g. https://bookdown.org/yihui/bookdown/cross-references.html)

When I use the `\@ref(label)` format in a `Rmd` document with output type `rmdformats::readthedown` (e.g. https://raw.githubusercontent.com/richarddmorey/RprojectDemo/master/papers/Rpaper1/text/html_paper/paper_html.Rmd) I just get `@ref(label)` in the text. Is there any way of getting cross-references to work?

**Comment by juba** [comment]
Hi,

To make cross references and other `bookdown` specific features work, you must put the `use_bookdown` argument in your document preamble 👍 

```
output: 
  rmdformats::readthedown:
    use_bookdown: true
```

Let me know if it doesn't work.

**Comment by gueyenono** [comment]
I tried the solution and it works. Thank you.
