### ISSUE TITLE
lightbox, thumbnails and gallery options available for default html_document?

### ISSUE THREAD

**Issue by markdumke** [juba/rmdformats#36]
First of all great work! 
I'd like to use the lightbox, thumbnails and gallery option in the default html_document in R Markdown. Is this possible? Couldn't figure out, how to create a template for this. Can you help me?

**Comment by juba** [comment]
Those options are not part of the standard html_document template, so there 
is no way to use them with it, unless they would be implemented in the  
rmarkdown package...

**Comment by markdumke** [comment]
Ok, thanks for your answer. Then I will try to make a new template based on html_document to make this possible :)
