### ISSUE TITLE
readthedown colors

### ISSUE THREAD

**Issue by tspeidel** [juba/rmdformats#37]
Thanks for contributing these wonderful themes to the R community!

Not really an issue. I was wondering how to change the colors of readthedown theme to reflect the default readtheorg (blue/black). I understand I can customize elements by placing a css file, but I'm not sure what to write in the css.
Thanks

PS I see someone asked the same question on stackoverflow: https://stackoverflow.com/questions/42935320/how-to-change-the-color-theme-on-rmdformats-readthedown

**Comment by juba** [comment]
Hi, and thanks for the link to the StackOverflow question.

To change the default color for titles and other elements, you indeed have to provide a custom CSS file to redefine the default CSS elements defining color. 

If think the following should be enough :


    #main .nav-pills > li.active > a,
    #main .nav-pills > li.active > a:hover,
    #main .nav-pills > li.active > a:focus {
       background-color: #22983B;
    }
    
    #main .nav-pills > li > a:hover {
      background-color: #22983B;
    }
    
    h1,h2,h3,h4,h5,h6,legend{
        color: #22983B;
    }
    
    #nav-top span.glyphicon {
      color: #22983B;
    }
    
    #table-of-contents header{
        color:#22983B;
    }
        
    #table-of-contents h2{
        background-color:#22983B;
    }
    
    #main a {
        background-image: linear-gradient(180deg,#d64a70,#d64a70);
        color:#c7254e;
    }
    
    a:hover{
        color:#3d1308
    }
    
    a:visited{
        color:#3d1308
    }

Customize and add this to a `custom.css` file in your `Rmd` file directory, and add `css: custom.css` in your preamble.

**Comment by tspeidel** [comment]
Thanks so much!

**Comment by tspeidel** [comment]
I can't find a way to modify the background color from light gray #FCFCFC to white/transparent.

![image](https://user-images.githubusercontent.com/6731198/55836555-1ac60200-5adc-11e9-9c31-816fa6068eaa.png)

What should I add in the css?

**Comment by juba** [comment]
This should work : 

```css
#content {
  background-color: #FFF;
}
```

If it doesn't, try ` background-color: #FFF !important;`.

**Comment by GreysiArrelucea** [comment]
How can I change the background from the left, the part of brown and blue?

**Comment by juba** [comment]
You should be able to change the background color by using `#sidebar` and `#sidebar h2` selectors.

**Comment by GreysiArrelucea** [comment]
Thank you so much! :')
