### ISSUE TITLE
Do not split into pages in material

### ISSUE THREAD

**Issue by Maiae** [juba/rmdformats#40]
Is it possible to add an option in the `material` format so pages are not split at each `<h1>` and all cards appear in one page like in `html_clean`?

**Comment by juba** [comment]
Hi,

Thanks for the suggestion. I added a `cards` argument to the `material` template in the development version of `rmdformats`. If you put `cards: false` in your YAML preamble, all the cards should be visible. Could you tell me if it works for you ?

Thanks !

**Comment by Maiae** [comment]
Thanks,
It works!  
One minor thing is that the left hand side menu is no longer highlighted for the selected card.  

![rmd_material_cards](https://user-images.githubusercontent.com/3907890/42854662-4ee95ae6-8a80-11e8-8046-7daab79cae34.JPG)

**Comment by juba** [comment]
Yes you're right !

I think this should be fixed in the development version...
