### ISSUE TITLE
material design error

### ISSUE THREAD

**Issue by leo-filgueira** [juba/rmdformats#41]
When I create a new Rmarkdown from template (HTML material design template), I get an error when I press knit. The YAML is this:

```
---
title: ""
date: "`r Sys.Date()`"
output:
  rmdformats::material:
    highlight: kate
---

```
The error:

```
pandoc.exe: Could not fetch https://fonts.googleapis.com/css?family=Roboto:300,400,500,700
TlsExceptionHostPort (HandshakeFailed (Error_Misc "user error (unexpected type received. expecting handshake and got: Alert [(AlertLevel_Fatal,HandshakeFailure)])")) "fonts.googleapis.com" 443
Error: pandoc document conversion failed with error 67
```

My `sessionInfo()`:

```
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252   
[3] LC_MONETARY=Portuguese_Brazil.1252 LC_NUMERIC=C                      
[5] LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.19     rstudioapi_0.8   bindr_0.1.1      knitr_1.20      
 [5] magrittr_1.5     tidyselect_0.2.4 xtable_1.8-3     R6_2.3.0        
 [9] rlang_0.2.2      stringr_1.3.1    highr_0.7        dplyr_0.7.6     
[13] tools_3.5.0      xfun_0.3         miniUI_0.1.1.1   htmltools_0.3.6 
[17] assertthat_0.2.0 yaml_2.2.0       rprojroot_1.3-2  digest_0.6.17   
[21] tibble_1.4.2     crayon_1.3.4     bookdown_0.7     bindrcpp_0.2.2  
[25] shiny_1.1.0      purrr_0.2.5      questionr_0.6.3  later_0.7.5     
[29] promises_1.0.1   glue_1.3.0       evaluate_0.11    mime_0.6        
[33] rmarkdown_1.8    stringi_1.1.7    pillar_1.3.0     compiler_3.5.0  
[37] rmdformats_0.3.3 backports_1.1.2  httpuv_1.4.5     pkgconfig_2.0.2 
```

**Comment by juba** [comment]
This is a network error when trying to connect to Google Web fonts. What's happening if you try to open the URL directly in a browser ?

https://fonts.googleapis.com/css?family=Roboto:300,400,500,700

**Comment by leo-filgueira** [comment]
It opens:

![](https://user-images.githubusercontent.com/33987660/46891848-b3d3d300-ce41-11e8-99d6-322ca398fec9.png)

**Comment by juba** [comment]
Strange, this could be related to your version of pandoc : 

https://github.com/mkearney/mizzourahmd/issues/1

What RStudio version do you run ?

**Comment by juba** [comment]
And what gives `rmarkdown::pandoc_version()` ?

**Comment by leo-filgueira** [comment]
It gives 1.19.2.1

I've edited my previous comment to say my pandoc version.

**Comment by juba** [comment]
Ah, so I think the problem may come from here, your pandoc version is to old. Do you have several pandoc installation on your computer ?

**Comment by leo-filgueira** [comment]
This I don't know.
I've seen just now a way to update pandoc with `installr::install.pandoc()`.
Should I do this?

**Comment by juba** [comment]
Ah yes, didn't know about this, you can give it a try...

**Comment by leo-filgueira** [comment]
I'm trying to download version 2.0, but via `download.file`. 
`installr::install.pandoc()` didn't work here.

**Comment by juba** [comment]
Is there not a more recent version ? Int his issue they say that issue may have been solved around version 2.2 : 

https://github.com/mkearney/mizzourahmd/issues/1

I'm currently running pandoc 2.2.1 from RStudio preview 1.2.1015

**Comment by leo-filgueira** [comment]
There's pandoc 2.3.1. I'll try

**Comment by leo-filgueira** [comment]
I've updated to pandoc version 2.3.1 (downloaded [here](https://github.com/jgm/pandoc/releases)) and now I can knit Rmd with material design. 

I'm trying to reproduce this [example](https://raw.githubusercontent.com/juba/rmdformats/master/resources/examples/material/material.Rmd) and I've noticed some differences. Look:

![reproduce](https://user-images.githubusercontent.com/33987660/46896101-da016f00-ce51-11e8-82f9-26e1c5929643.png)

While the example looks like this:

![example](https://user-images.githubusercontent.com/33987660/46896111-e4236d80-ce51-11e8-8ad9-3efd90481aa2.png)

**Comment by juba** [comment]
Strange, it's working fine here... Could you send me the generated HTML file ?

**Comment by leo-filgueira** [comment]
I tried just now and html was equal the example. I think it's all ok now
