### ISSUE TITLE
material format responsive

### ISSUE THREAD

**Issue by ecodiv** [juba/rmdformats#44]
The material format does not seem to be responsive. Is it possible to make it responsive?

**Comment by juba** [comment]
Yes, you're right, unfortunately it is not. Obviously it would be very useful to make it responsive, but I'm not sure I'll be able to work on this in a foreseeable future...

**Comment by ecodiv** [comment]
OK, thanks. It is such a nice template, hopefully somebody can pick this up. I had a look myself, but it unfortunately goes beyond my understanding. For now I will go for another nice template from your package :-).  Thanks for making this package!

**Comment by dgibert17** [comment]
Hello! I am having loads of problems to render into material. I had different errors, solved them, now it works but the output has a bad format. I do not know how to fix it.

Warning message:
MathJax doesn't work with self_contained when not using the rmarkdown "default" template.

That is the only thing I get when rendering. Could you give me a hand please?

**Comment by juba** [comment]
I can help, but I would need a reproducible example for that. 

The warning about Mathjax is common, it is not the cause of your problem.

**Comment by dgibert17** [comment]
> I can help, but I would need a reproducible example for that.
> 
> The warning about Mathjax is common, it is not the cause of your problem.

Thanks for such a quick reply **Juba**! 

This is an image of how it looks.

![capture](https://user-images.githubusercontent.com/32716046/53960471-b67fdf00-40e6-11e9-8f19-8b00af9af172.PNG)

This is the example I want it to look like:

![capture2](https://user-images.githubusercontent.com/32716046/53960395-80425f80-40e6-11e9-8735-14f20cfcc747.PNG)

**Comment by juba** [comment]
Thanks.

Could you send me your rmarkdown file or a sample of it which would reproduce the problem ?

**Comment by dgibert17** [comment]
Thank you!

Here you can find the code.

[house-prices-kaggle.zip](https://github.com/juba/rmdformats/files/2941464/house-prices-kaggle.zip)

**Comment by juba** [comment]
Ok, the problem is that your document is missing a level 1 heading. In `material` you have to use this level of headings to structure the documents, otherwise will not recognize its structure.

Replacing `##` with `#` in your file should work.

**Comment by dgibert17** [comment]
> Ok, the problem is that your document is missing a level 1 heading. In `material` you have to use this level of headings to structure the documents, otherwise the template will not recognize its structure.
> 
> Replacing `##` with `#` in your file should work.

Works like a charm! Thank you very much for your help and the quick responses!

**Comment by juba** [comment]
You're welcome, glad it is solved !
