### ISSUE TITLE
YAML templates missing blank lines at end of file?

### ISSUE THREAD

**Issue by THOMASELOVE** [juba/rmdformats#47]
It appears as though the YAML templates are missing a blank line at the end of the file. So R Studio users are getting the following:  incomplete final line found on '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmdformats/rmarkdown/templates/readthedown/template.yaml

It looks like this happens with html_docco, material and html_clean's template.yaml files as well.

**Comment by juba** [comment]
Strange, I didn't notice this error before and it seems I'm not able to see it on my system.

Anyway, I think this should be fixed, don't hesitate to reopen this issue if it isn't.

Thanks for taking the time to report the problem !

**Comment by juba** [comment]
Did you try the latest development version ?

```r
remotes::install_github("juba/rmdformats")
```

**Comment by matthijsvanderloos** [comment]
Yes, I installed the version from GitHub.

**Comment by juba** [comment]
Ah, yes, there's a tabulation at the end of the first one. I just commited a fix, could you please test if the warning message is gone for good this time ?

Sorry not to have spotted it, but I don't see the warnings here...

**Comment by matthijsvanderloos** [comment]
Just installed the latest dev. version and the warning message is gone now.

Thanks!

**Comment by THOMASELOVE** [comment]
Thanks. My warning message has also disappeared after installing the latest development version.

**Comment by Neofiji** [comment]
Hi,
I have tried to install the latest version as follows:
remotes::install_github("juba/rmdformats")
then
Enter one or more numbers, or an empty line to skip updates:1
but getting
Error: Failed to install 'rmdformats' from GitHub:
  (converted from warning) installation of package ‘fs’ had non-zero exit status

and getting the reccurent warning:
1: In readLines(con) :
  incomplete final line found on 'C:/Users/Administrateur/Documents/R/win-library/3.6/rmdformats/rmarkdown/templates/downcute/template.yaml'

Any advice plz? Tx

**Comment by juba** [comment]
Hi, it seems that the error is not linked to `rmdformats` but to the `fs` package. Maybe try to install it directly, fix any error and retry to install `rmdformats` after that ?

**Comment by Neofiji** [comment]
Tx @juba. Had to jump through other similar hoops but it's sorted.
