### ISSUE TITLE
readthedown: dropdown don't work

### ISSUE THREAD

**Issue by dktanwar** [juba/rmdformats#53]
# A dropdown menu {.tabset .tabset-dropdown}

**Code to reproduce**

```
```{r, result = 'asis'}
for(i in 1:10){
cat("\n \n")
  cat(paste("##", "test", i))
  cat("\n \n")
  plot(i:10)
  cat("\n \n")
}
```

**Comment by juba** [comment]
Indeed, dropdown tabsets are not supported in `rmdformats` (yet). I may take a look at it in the coming weeks...

Thanks for taking the time to report the problem.

**Comment by juba** [comment]
So, I'm well aware this issue has been opened more than a year ago, but it should now be fixed in the development version.

Sorry for the awfully long delay, and thanks again for taking the time to report the issue.
