### ISSUE TITLE
[Question] How to display level 2 headers in rmdformats:: material menu? 

### ISSUE THREAD

**Issue by ryanlohyp** [juba/rmdformats#57]
Hi Juba,

I notice that the menu in rmdformats::material does not include second level headers. May I know what can I do to show them?

Thank you.

**Comment by juba** [comment]
Unfortunately this is not possible in this template. If you'd like to implement it, you would have to modify the template files, surely both HTML and JavaScript, and I'm not sure the JavaScript modification would be trivial.

**Comment by ryanlohyp** [comment]
Thank you Juba for the clarification.

**Comment by ryanlohyp** [comment]
Dear Juba,

I tried my own modification and seems like it does not work for me.

May I know what is your recommendation to modify the codes? 

Thanks

**Comment by juba** [comment]
Unfortuantely, after a quick look, I don't think this will be possible. You would have to modify the template to make it accept a `toc_depth` argument, but even with this, adding more than one level in the menu breaks the cards navigation. So this means you would also have to greatly modify the underlying JavaScript code.
