### ISSUE TITLE
make links work between cards

### ISSUE THREAD

**Issue by ds-jim** [juba/rmdformats#58]
Hi,

Is it possible to get links to work between the cards? In the example below within card links work great, however, external links do not.

Thank you, Jim

```
---
title: "Aurora Trial"
output: 
      rmdformats::material
---

#Card 1

[Within card link](#card_1)
  
[Different card link](#card_2)

### <a id="card_1"></a>Your leader
```{r}
plot(mtcars)
```

#Card 2

## <a id="card_2"></a>Target of external link
```{r}
plot(cars)
```

```

**Comment by juba** [comment]
Unfortunately the only way I see to make it work for the moment is to disable the cards by addings `cards: FALSE` in your preamble. I admit it is not ideal, I tried to fix it with `cards: TRUE` but the fact that anchors are already used to manage the cards makes it quite difficult.

**Comment by ds-jim** [comment]
Ahh, that's a shame. Thanks for checking it out for me. Unfortunately, I want the cards in use as they're really nice defining clear splits in the report structure.
