### ISSUE TITLE
Cannot change toc level for readthedown?

### ISSUE THREAD

**Issue by vkartha** [juba/rmdformats#61]
Tried setting the following YAML preamble in my RMD file:

---
title: "Test RMD"
date: "9/13/2019"
output: rmdformats::readthedown
---

This generates the correct formatted html output, but the TOC generated does not support levels over 2. How can I change the TOC level to, say, 4?

I tried  :

---
title: "Test RMD"
date: "9/13/2019"
output: rmdformats::readthedown:
        toc_level: 4
---

But that returned an error

**Comment by juba** [comment]
The argument is called `toc_depth`, not `toc_level`. However only levels 1 to 3 have an effect. 

In any cases, the error you see is caused by your preamble, which must be formatted like this : 

```
output:
  rmdformats::readthedown:
    toc_depth: 1
```
