### ISSUE TITLE
Thumbnail option

### ISSUE THREAD

**Issue by chadsmitharc** [juba/rmdformats#62]
Is it possible to render a figure w/o thumbnails, and the rest of the figures in the rmd with thumbnails?

Thanks!

**Comment by juba** [comment]
It's not really elegant, but the following workaround should work by using the `out.extra` knitr option : 

    ```{r, out.extra='style="width:auto;"'}
    plot(...)
    ```

If you want to also get rid of the border : 

    ```{r, out.extra='style="width:auto; border: none;"'}
    plot(...)
    ```

Let me know if it doesn't work for you.
