### ISSUE TITLE
Dt tables target="row" not working with readthedown

### ISSUE THREAD

**Issue by davidvilanova** [juba/rmdformats#63]
The following exemple will not work as expected. No rows will be colored. It will work without the readthedown theme.

Note that target="cell" will work so i guess the problem has to do with target="row" only.

```
---
output:
 rmdformats::readthedown:
    highlight: kate
    oc_depth: 3
    self_contained: true
    number_sections: true
    code_folding: "hide"     

---

```{r}
library(DT)
df <- cbind(runif(100), rbinom(100,1,.5), runif(100))
datatable(df) %>% formatStyle(
  'V2',
  target = 'row',
  backgroundColor = styleEqual(c(0, 1), c('gray', 'yellow'))
)

datatable(df) %>% formatStyle(
  'V2',
  target = 'cell',
  backgroundColor = styleEqual(c(0, 1), c('gray', 'yellow'))
)

> > packageVersion("DT")
> [1] ‘0.10.1
> packageVersion("rmdformats")
[1] ‘0.3.5’
```

**Comment by juba** [comment]
You're right, there was a conflict between the `readthedown` CSS and `DT` row coloring. This should now be fixed in the development version.

Thanks for taking the time to report the issue.

**Comment by davidvilanova** [comment]
Thanks for the fix !!!!!
