### ISSUE TITLE
Prevent Tabbed Sections from Showing Up on Table Contents

### ISSUE THREAD

**Issue by poonv** [juba/rmdformats#64]
When using toc with default html r markdown, tabbed sections do not show on the toc. However in rmdformats::readthedown:, this does not seem to be the case. Is there anyway to hide these tabbed sections from the toc in rmdformats?

Thanks!

![screenshot1](https://user-images.githubusercontent.com/57682391/69270386-b0079980-0b87-11ea-9b79-8ed775788776.PNG).

**Comment by juba** [comment]
Yes, you were right. This should now be fixed in the development version.

Thanks for taking the time to report the issue !
