### ISSUE TITLE
Transfer `questionr` from Imports to Suggests? 

### ISSUE THREAD

**Issue by rCarto** [juba/rmdformats#65]
Hi, 
First of all, thank you for this nice package, I use it a lot!

Only 3 functions from `questionr` are used in the package, in `pilltabs()`. 
And in this function,  the installation of `questionr` is tested: 

https://github.com/juba/rmdformats/blob/6abadad064076bcdad12b9cb1c8d74d12b97cf26/R/pilltabs.R#L33
 
`questionr` is also a nice package that comes with various dependencies but is only very marginally used in `rmdformats`. 

If `questionr` was transferred to Suggests `rmdformats` would gain (lose) a lot in terms of dependencies. 

``` r
library(miniCRAN)
# questionr dependencies 
questionr <- pkgDep("questionr", suggests = FALSE, enhances = FALSE)
# rmdformats dependencies without questionr
rmdformats <- pkgDep(c('knitr','rmarkdown','bookdown','htmltools'), 
                     suggests=FALSE, enhances = FALSE)
# package saving if questionr is tranfered to Suggests
setdiff(questionr, rmdformats)
#>  [1] "questionr"   "shiny"       "miniUI"      "rstudioapi"  "classInt"   
#>  [6] "labelled"    "e1071"       "class"       "KernSmooth"  "haven"      
#> [11] "dplyr"       "httpuv"      "xtable"      "R6"          "sourcetools"
#> [16] "later"       "promises"    "crayon"      "fastmap"     "MASS"       
#> [21] "assertthat"  "pkgconfig"   "tibble"      "tidyselect"  "BH"         
#> [26] "plogr"       "forcats"     "hms"         "readr"       "ellipsis"   
#> [31] "vctrs"       "clipr"       "cli"         "fansi"       "pillar"     
#> [36] "purrr"       "utf8"        "backports"   "zeallot"
```

<sup>Created on 2019-12-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

What do you think?

**Comment by juba** [comment]
I think you're absolutely right ! The corresponding `requireNamespace` was even already in place, I think `questionr` should have been into `Suggests` from the beginning.

It should be fixed in the development version now, thanks for taking the time to make this suggestion.

**Comment by rCarto** [comment]
Great!
