### ISSUE TITLE
add hyperlink to logo above TOC for readthedown theme

### ISSUE THREAD

**Issue by derekmichaelwright** [juba/rmdformats#67]
In my CSS file I have this code to specify a logo to go in the top left corner above the table of contents:

#table-of-contents h2{
    background: url("Logo.png");
}

Is it possible to make this image a clickable link? similar to what is asked here:
https://github.com/fniessen/org-html-themes/issues/80

something like this perhaps:

#table-of-contents h2{
    background: url("Logo.png");
    background-link: url("http://www.website.com");
}

**Comment by juba** [comment]
No, this is not possible for the moment unfortunately. There is no `background-link` CSS property.

You would have to modify the template itself to do this I think.
