### ISSUE TITLE
readthedown: Links not underlined

### ISSUE THREAD

**Issue by jemus42** [juba/rmdformats#7]
It works in the [beginning of the document](http://stats.jemu.name/theincomparable/results_incomparable.html#introduction)
but not at the [end of the document (last line linking to this very repo)](http://stats.jemu.name/theincomparable/results_incomparable.html#acknowledgements), and I'm assuming something in the middle broke it, but I don't know what could have.

**Comment by juba** [comment]
Hi,

You're right, links underlining with background positioning seems quite fragile. The CSS styling of the `<a>` in your documents are exactly the same, put rendering is different.

So I switched back to a simple link coloring, while keeping the same `hover` effect.

What do you think of it ?

**Comment by jemus42** [comment]
I'm happy with that, I think I prefer full text coloring for links now that I see the difference.

Thanks!
