### ISSUE TITLE
code_download option passed to html document from rmdformats seems to silently fail

### ISSUE THREAD

**Issue by ltrainstg** [juba/rmdformats#70]
# Problem
The rmdformats function passes the code_download: True argument to the html_document, but it does not actually create a download link. It does create a long string of text at the bottom of the document.

Since the argument doesn't work it should probably produce an error or a warning that says this feature is not implemented and will be set to FALSE. 

## Default HTML  Behavior 
![image](https://user-images.githubusercontent.com/16125810/76897402-ee207b80-6850-11ea-81c5-c797cfbd2d5c.png)

## Readthedown Behavior
![image](https://user-images.githubusercontent.com/16125810/76897382-e1038c80-6850-11ea-8edd-d76c20a084d2.png)

````
---
date: "`r Sys.Date()`"
output:
  html_document:
    code_download: TRUE
  rmdformats::readthedown:
    code_download: TRUE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

fillerText <- "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

```

# Main Header

## 1
`r fillerText`

# Second Header
````

**Comment by juba** [comment]
I think `code_download` should now work in all the templates in the development version. If not, don't hesitate to reopen this issue.

Thanks for taking the time to report the problem !
