### ISSUE TITLE
Facilitate placement of copyright/origin information on material design pages

### ISSUE THREAD

**Issue by dmkaplan2000** [juba/rmdformats#71]
Hi,

It would be nice to able to easily include basic origin and copyright information on material design pages. I tried using include-after in the YAML header:

`include-after: "Created with <a href=\"https://github.com/juba/rmdformats\">rmdformats</a>"
`
But this seems to have created an additional "row" of the page that adds an extra vertical scroll bar for the entire page on my screen, whereas one probably wants something that floats naturally at the bottom of the page. 

If there is an easy solution to this, perhaps that can be added to the template.

Thanks,
David

**Comment by juba** [comment]
Hi,

Did you really get something by using `include-after` in the preamble ? It seemed to me that the syntax is rather something like :

```
    includes:
      before_body: /tmp/include.html
      after_body: /tmp/include.html
```

Anyway, I changed the includes position in the latest development version, maybe it can be a bit better...

**Comment by dmkaplan2000** [comment]
Hi,

Yes, include-after did work. That doesn't necessarily mean that it is 
the most appropriate way to do it and that the other way wouldn't work, 
but when I saw the $include-after in the template I just threw that in 
the YAML header and it worked. include-after lets me add individual 
lines of HTML, whereas include: after_body: seems to be for including an 
entire HTML file. Presumably, the file is parsed into an array of 
include-after's and so either specifying that with an HTML file or going 
directly to include-after works.

With the new placement of include-after, include-after content is placed 
outside the white box that contains the "card" and just below it, which 
is a definite improvement. It would be better if there was a way to 
force that content to be at the bottom of the page if the card is 
smaller than the screen, but I haven't found a good way to achieve that.

Thanks,
David

**Comment by juba** [comment]
Ah, yes, you have to put `include-after` at the top level of the YAML preamble, not as a template option.

I have once more changed the includes placement, and I think you may achieve what you want by adding the following styles in you document : 

```css
  .pages {
    display: flex;
    flex-direction: column;
    min-height: 100%;
    justify-content: space-between;
  }
```

**Comment by dmkaplan2000** [comment]
¡Excelente! With this magic, the text appears at the bottom of the 
screen. The one really minor issue is that the text is padded on the top 
by 64px, which it inherits from the row it is in. I don't think you can 
change this padding inside Rmarkdown without changing the padding for 
all rows. Or perhaps I am mistaken? In any case, this is a very minor issue.

Thanks a bunch!
David

**Comment by dmkaplan2000** [comment]
Hmmm, that does move the text closer to the card, but it does so by 
moving the text off the bottom of the page. Probably best to leave it as 
it was before. It is only a bit annoying when the bottom of the card is 
within 64px of the bottom of the page...

Cheers,
David

**Comment by juba** [comment]
Did you try with `margin-top` too ?

**Comment by dmkaplan2000** [comment]
Yes, margin-top was the one that seemed to do something. padding-top 
seemed to have no effect.

Cheers,
David

**Comment by juba** [comment]
Yes you're right. I just added an `include-after` id to the corresponding `row`, so you should be able to do things like these : 

```css
  .pages {
    display: flex;
    flex-direction: column;
    min-height: 100%;
    justify-content: space-between;
  }
  .pages > row {
    padding-bottom: 0px;
  }
  #include-after {
    padding: 0px;
  }
```

(not really clean, but it should work)

**Comment by dmkaplan2000** [comment]
As you said, effective but not particularly pretty. Thanks for the help!
