### ISSUE TITLE
fig.align='center' not working in material template

### ISSUE THREAD

**Issue by hbaniecki** [juba/rmdformats#73]
Hi, love this package!

I am using `rmdformats::material` and setting `fig.align='center'` in chunk options doesn't work. Is&nbsp;it&nbsp;a&nbsp;bug? It would be nice to have `fig_align: center` option like those below.
https://github.com/juba/rmdformats/blob/df6254972940e9125d4c802ec0f5d46f97f95712/resources/examples/material/material.Rmd#L9-L12

**Comment by juba** [comment]
`fig.align = 'center'` doesn't work if you have `thumbnails: true` in your preamble. Maybe you could try to disable it ?

**Comment by hbaniecki** [comment]
`thumbnails: false` did resolve this problem. Thanks!
