### ISSUE TITLE
Links don't work across material cards using bookdown

### ISSUE THREAD

**Issue by senanu** [juba/rmdformats#74]
# Problem
cross-references to figures in 'material' don't seem to work when
`cards: true`. 
# Desired result
`\@ref(fig:foo)` should provide a working link to figure foo. It produces what looks and seems like a link, but the link doesn't connect to the right place unless the 'card' is open. 
# Other details
I am using bookdown to support this, and they work fine with `cards: false`.
# Minimal example for demonstration
````
---
title: "A test of links"
date: "`r Sys.Date()`"
output:
  rmdformats::material:
    highlight: kate
    cards: true
    use_bookdown: true
---

```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Part 1

This test of links uses the template file structure. 

A link to the first pic (\@ref(fig:r-pic))

A link to the second (\@ref(fig:r-pic2))

```{r r-pic, include=TRUE, echo=FALSE, out.width='30%', fig.align="center", fig.cap="R logo"}
knitr::include_graphics("https://www.r-project.org/Rlogo.png")
```

# Part 2

Another logo!

```{r r-pic2, include=TRUE, echo=FALSE, out.width='50%', fig.align="center", fig.cap="2nd R logo"}
knitr::include_graphics("https://www.r-project.org/Rlogo.png")
```


A link to the first pic (\@ref(fig:r-pic))

A link to the second (\@ref(fig:r-pic2))

````

**Comment by juba** [comment]
Yes, it is the same problem as #58, that's a limitation of `material` with cards enabled, internal links don't work. You should be able to add an internal link to a card, but not to an element inside a card.

So the only way to make it work is to disable cards...

Thanks for taking the time to report the problem with a reproducible example, and sorry for the lack of solution.

**Comment by senanu** [comment]
I feared something like that. Its a pity because the cards make the layout so clean. Well, I guess `cards: false` is a not-too-distant second! 
Thank you
