### ISSUE TITLE
toc flexibility

### ISSUE THREAD

**Issue by mayer79** [juba/rmdformats#75]
Great package! 
I wanted to ask if it would be possible to allow the user to set his or her own `toc` related settings. 
E.g. in `material`, the only option seems to be `toc = TRUE, toc_depth = 1`. I'd love to use e.g. `toc_depth = 2` and `toc_float`, but maybe this is not foreseen?

**Comment by mayer79** [comment]
Okay, thanks for clarifying.

**Comment by yasineahmed** [comment]
Has anyone found a work around for this?

**Comment by juba** [comment]
You mean adding support to `toc_depth` in `material` ? Not to my knowledge.
