### ISSUE TITLE
Using rmdformats for vignettes but not self_contained

### ISSUE THREAD

**Issue by mages** [juba/rmdformats#78]
I'd like to use `rmdformats` to format the vignette of my [`googleVis`](http://github.com/mages/googleVis) R package. Knitting the vignette in RStudio works well, but when I build and install the package via the command line the formatting of `rmdformats` is lost. It appears to me that this is due to my YAML header, where I set `self_contained: false`.  Does this setting have to be `true`?

**Comment by juba** [comment]
Yes, I think that HTML vignettes must always be `self_contained`.

Be careful that using an `rmdformats` theme will make the vignette size potentially much bigger, which can be a problem for inclusion in a package. I tend to always use the specifically designed `html_vignette` theme for this :

https://rmarkdown.rstudio.com/docs/reference/html_vignette.html

**Comment by mages** [comment]
Thanks for your comments!
