### ISSUE TITLE
material: Active toc highlight misbehaves when tabbed content contains a plotly figure

### ISSUE THREAD

**Issue by greeco** [juba/rmdformats#79]
Thanks a lot for this wonderful template. 

I observe the problem with `cards: false` and when a second (or higher) tab of a tabbed content contains the `plotly` figure.

The active toc highlight jumps to the top when the tab that contains the plotly figure is selected and the page is scrolled to another section.

The same behavior can be observed with a `DT:datatable` instead of a `plotly` figure.

This behavior cannot be observed when using the `readthedown` template.

In the minimal example below: one has to select the second tab of "Third section" and scroll.
[minimal_example.txt](https://github.com/juba/rmdformats/files/5077635/minimal_example.txt)

**Comment by juba** [comment]
Small update : it is not due to a JavaScript interaction, but to a change on the global body height. The problem occurs also if the second tab only includes a static plot of a different height.

**Comment by juba** [comment]
Confirmation : scrollspy only works correctly if the element it is applied to is positioned with `position: relative`. But in `material` it can only be applied to the `.pages` div, which must be absolutely positioning for the layout to work.

So unless someone else has a workable solution, I'll be unable to fix this and will close this issue for now.
