### ISSUE TITLE
caption position of pilltabs in readthedown

### ISSUE THREAD

**Issue by dmenne** [juba/rmdformats#8]
When I use
```
data(airquality)
tab <- table(airquality$Month, airquality$Ozone > 25)
pilltabs(tab)
```
in a fresh readthedown document, I get an ugly positioning of the caption:

![2016-03-21 21_05_43-mozilla firefox](https://cloud.githubusercontent.com/assets/506275/13932586/f9700c78-efa8-11e5-9c4a-c9bc106ef3a3.png)

Version:
2016-02-26

**Comment by juba** [comment]
Yes, you're right, I'll look into it.

**Comment by juba** [comment]
Should be fixed. Thanks for reporting.

**Comment by dmenne** [comment]
Next time I measure reaction time in milliseconds :-)
