### ISSUE TITLE
CSS precedence and leaflet map in readthedown

### ISSUE THREAD

**Issue by dicorynia** [juba/rmdformats#80]
Hi, thanks for your nice package, readthedown is really appreciated by my users.

However I have a glitch when using a leaflet map with this format : some map controls are weird ; I don't know whether it's on the leaflet side or readthedown side, but it doesn't happen with material or html_clean...

Normal raw map :
![2020-11-06 11_25_55-Mozilla Firefox](https://user-images.githubusercontent.com/31208891/98356035-45af6980-2023-11eb-88a0-37d08c231050.png)

With readthedown : fullscreen button and layers control icon disappear.
![2020-11-06 11_27_07-CA Mâconnais Beaujolais Agglomération](https://user-images.githubusercontent.com/31208891/98356082-59f36680-2023-11eb-81ff-cfafe60078b9.png)

Any idea on what I should edit ?
Thanks

**Comment by juba** [comment]
Maybe I could speak french, looking at the maps, but as I'm not sure I'll continue in english :-) 

The problem surely comes from interactions with the readthe down CSS, I already met this knid of bugs. Would it be possible for you to send me a problematic HTML file so that I could take a look ?

By the way, I just published two others HTML templates, not sure if they would have the same problems.

Thanks for taking the time to report the issue !

**Comment by juba** [comment]
Well, in fact I can reproduce the problem myself. I just pushed a small update to the development version which may fix the issue. Could you please let me know if that is not the case ? Thanks !

**Comment by dicorynia** [comment]
But alors you are french ;-)
(j'ai écrit en anglais par souci d'"universalité", mais je poursuis en français)

Ci-joint un document reproductible.

    ---
    title: "Test leaflet rmdformat"
    date: "`r Sys.Date()`"
    output:
      rmdformats::readthedown:
        highlight: kate
    editor_options: 
      chunk_output_type: console
    ---
    
    
    ```{r setup, echo=FALSE, cache=FALSE}
    library(knitr)
    library(rmdformats)
    library(sf)
    library(leaflet)
    library(leaflet.extras)
    ```
    
    # Map
    
    ```{r}
    
    nc <- st_read(system.file("shape/nc.shp", package="sf"))
    
    leaflet() %>% 
      addProviderTiles("OpenStreetMap.Mapnik") %>% 
      addPolygons(data = nc) %>% 
      addLayersControl(baseGroups = c("OSM"),
                       overlayGroups = c("NC")) %>% 
      addFullscreenControl()
    
    ```

**Comment by dicorynia** [comment]
Zut pas vu la réponse. Merci

**Comment by juba** [comment]
N'hésitez pas à tester voir si ça marche. Désolé pour le temps passé sur l'exemple reproductible !

**Comment by dicorynia** [comment]
Merci. Il n'y a plus les bordures rouges par contre les icônes n'apparaissent pas...

![2020-11-06 16_21_14-Test leaflet rmdformat](https://user-images.githubusercontent.com/31208891/98382947-2973f280-204c-11eb-86f0-3213a1589d18.png)

**Comment by juba** [comment]
Ah exact, bien vu. Je viens de publier encore une nouvelle mise à jour. Pouvez-vous tester à nouveau à l'occasion ? Merci !

**Comment by dicorynia** [comment]
C'est parfait ! Merci pour cette réactivité !
