### ISSUE TITLE
Feature request for downcute to go to toc depth of 3. 

### ISSUE THREAD

**Issue by ltrainstg** [juba/rmdformats#81]
# Problem

When you try to use TOC depth of 3 or more when using downcute the TOC looks off since it looks like it makes the section, but does not display it with the current CSS code. Can this be added? 

# Example Image

Notice the TOC has a small but where it shows the next entry. 
It flashes briefly on the screen before condensing so I know the TOC is there, but the expected drop down behavior is not there. 

Since I'm at the 3rd level is should show Section 5 in the TOC. 

![image](https://user-images.githubusercontent.com/16125810/99127051-95aea300-25c4-11eb-8d7d-b761884aad6c.png)

# Template Example
Looking at the template you linked it looks like it can do a 3rd level.
https://docute.org/guide/customization#navbar
![image](https://user-images.githubusercontent.com/16125810/99127476-a7447a80-25c5-11eb-98ab-c4264d4e4e2f.png)

# Example Code. 

```
# ---
# title: "downcute template example"
# #subtitle: "With a subtitle"
# date: "`r Sys.Date()`"
# output:
#   rmdformats::downcute:
#     code_folding: show
#     self_contained: true
#     thumbnails: false
#     lightbox: true
#     toc_depth : 3
# ---
# 
# ```{r setup, include=FALSE}
# library(knitr)
# library(rmdformats)
# library(DT)
# ## Global options
# options(max.print = "75")
# opts_chunk$set(echo = FALSE,
# 	             cache = FALSE,
#                prompt = FALSE,
#                tidy = FALSE,
#                comment = NA,
#                message = FALSE,
#                warning = FALSE)
# opts_knit$set(width = 75)
# ```
# 
# # Code and tables
# 
# ## Syntax highlighting
# 
# Here is a sample code chunk, just to show that syntax highlighting works as expected.
# 
# ```{r sh, echo=TRUE, eval=TRUE}
# library(ggplot2)
# library(dplyr)
# not_null <- function (v) {
#   if (!is.null(v)) return(paste(v, "not null"))
# }
# data(iris)
# tab <- iris %>%
#   group_by(Species) %>%
#   summarise(Sepal.Length = mean(Sepal.Length),
#             Sepal.Width  = mean(Sepal.Width),
#             Petal.Length = mean(Petal.Length),
#             Petal.Width  = mean(Petal.Length))
# ```
# 
# 
# ## Verbatim
# 
# Here is the structure of the `iris` dataset.
# 
# ```{r iris_str, echo=TRUE}
# str(iris)
# ```
# 
# 
# ### Level 3
# Here is the structure of the `iris` dataset.
# 
# ```{r iris_str0, echo=TRUE}
# str(iris)
# ```
# 
# 
# 
# ### Level 3
# Here is the structure of the `iris` dataset.
# 
# ```{r iris_str1, echo=TRUE}
# str(iris)
# ```
# 
# 
# 
# 
# ### Level 3
# Here is the structure of the `iris` dataset.
# 
# ```{r iris_str2, echo=TRUE}
# str(iris)
# ```
# 
# 
# 
# 
# ### Level 3
# Here is the structure of the `iris` dataset.
# 
# ```{r iris_str3, echo=TRUE}
# str(iris)
# ```



```

**Comment by juba** [comment]
Hi,

First of all, thanks for taking the time for this very detailed and precise issue.

Unfortunately I don't think I'll implement a three-level toc depth at package level, as I think it would be incompatible with the current TOC animation. However I think you could implement it on a per-document basis by adding the following CSS from an external file or directly in your Rmd (note that this will disable the animation) : 

```html
<style>
#toc ul.nav li ul li {
    display: none;
    max-height: none;
}

#toc ul.nav li.active ul li  {
    display: block;
    max-height: none;
}

#toc ul.nav li ul li ul li {
    max-height: none;
    display: none !important;
}

#toc ul.nav li ul li.active ul li {
    max-height: none;
    display: block !important;
}
</style>
```

**Comment by ltrainstg** [comment]
Thanks for looking into this so fast. I tried it and it works.
