### ISSUE TITLE
Math elements disrupt dynamic ToC

### ISSUE THREAD

**Issue by wigge206** [juba/rmdformats#84]
When using the `robobook` theme the dynamic ToC (on the left) breaks when I include math element, particularly equations (e.g. `$$T= \frac{\bar{x}_1-\bar{x}_2}{\sqrt{\frac{s^{2}_{1}}{N_1}+\frac{s^{2}_{2}}{N_{2}}}}$$`). Oddly it tends to tolerate some amount of inline math before breaking. 

My YAML is basic:
```
---
title: "Fun"
author: "me"
date: "29/12/2020"
output:
  rmdformats::robobook:
    toc_depth: 3
    highlight: default
---
```

Any thoughts on what is causing the break, or how to prevent it breaking?

**Comment by juba** [comment]
Hi,

Would you have a reproducible example of a document with a "broken" TOC ? I can't reproduce the problem even with the equation you give.

By the way you should only use `toc_depth: 2` in robobook, a value of 3 is not currently supported...

Thanks for taking the time to report the issue !

**Comment by wigge206** [comment]
Hi, 

The 'broken' nature is that the second level of list sometime does not appear. Typically the first time loading the HTML and the first click works as expected, then the collapsed list stop appearing. 

I have attached the html and rmd [Uploading Broken.zip…](here)

**Comment by juba** [comment]
Hmm it seems to work fine here. Did you try with the latest development version ?

**Comment by wigge206** [comment]
Even the html that I provided?
For me the 'including plots' level doesn't display. 

I just tried with the development version and still have the error

**Comment by juba** [comment]
Well unfortunately no, I tried with you Rmd file in RStudio, and with your html file in two different browsers, but I see no problem with the TOC.. The "inclding plots" entry seems to be displayed fine.

Whet browser do you use ?

**Comment by wigge206** [comment]
That is very peculiar. I have tested in on chrome, firefox and safari and all have replicated the error. When I disable mathJax the ToC behaved normally. 
If you add more text between headers so that the headers aren't in view on the same page does that help replicate the error?

**Comment by juba** [comment]
So, it seems I can reproduce the issue but only in a very specific case : after resizing the window when the scroll position is not at the top of the page. Then the TOC is messed up and doesn't sync with the display position. The problem is solved by resizing the window when on top of page.

 It seems to happen whether Mathjax is activated or not, though.

I'm not sure it is exactly the same problem as yours, but it seems specific to robobook : I can't reproduce with readthedown or downcute for example. I'm not sure what happens here, I'll try to take a look at it but can't guarantee I'll find the culprit.

Thanks again for taking the time to report the issue.

**Comment by juba** [comment]
Ok I'm really sorry, in think I can definitely reproduce the issue. I read your description too fast, and I didn't see that the problem appears when you click on TOC items, not just when scrolling. So I can see the same problem as you, and I think all the issues are related to a partial incompatibilty between the scrollspy script and the template markup. Still no solution yet, though.

Sorry again and thanks for your patience !

**Comment by juba** [comment]
So, I partly rewrote the robobook layout, and I think the issue may be resolved in the latest development version. If you have time to test it on your document, I'd be glad to have your feedback.
Thanks !

**Comment by wigge206** [comment]
Very impressed that you managed to debug this so quickly. That was the issue! Thank you.
