### ISSUE TITLE
How to change the color of rmdformats/readthedown theme?

### ISSUE THREAD

**Issue by coffeeCowLu** [juba/rmdformats#86]
i want to change the theme colour from Purple to blue. but i don't know how to do.

**Comment by juba** [comment]
Maybe take a look at #37. I think the CSS code there should still work.

**Comment by coffeeCowLu** [comment]
@juba Thank you for your prompt reply. 
i tested but not function .

---
title: <center>**test**</center>
subtitle: new version
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    code_folding: show
    thumbnails: true
    gallery: false
    fig_width: 4
    fig_height: 4
    df_print: kable
    fig_caption: yes
    use_bookdown: true
    ccs: styles.css
---


**styles.css**
#main .nav-pills > li.active > a,
#main .nav-pills > li.active > a:hover,
#main .nav-pills > li.active > a:focus {
   background-color: #22983B;
}

#main .nav-pills > li > a:hover {
  background-color: #22983B;
}

h1,h2,h3,h4,h5,h6,legend{
    color: #22983B;
}

#nav-top span.glyphicon {
  color: #22983B;
}

#table-of-contents header{
    color:#22983B;
}

#table-of-contents h2{
    background-color:#22983B;
}

#main a {
    background-image: linear-gradient(180deg,#d64a70,#d64a70);
    color: blue;
}

a:hover{
    color: blue
}

a:visited{
    color: blue
}


**sessionInfo()**
R version 3.6.0 (2019-04-26)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] processx_3.4.4 rmarkdown_2.6 

loaded via a namespace (and not attached):
[1] compiler_3.6.3  htmltools_0.5.0 tools_3.6.3     knitr_1.22     
[5] xfun_0.19       digest_0.6.25   ps_1.4.0        rlang_0.4.8    
[9] evaluate_0.14

**Comment by juba** [comment]
Hi, in your preamble you added `ccs: styles.css` instead of `css: styles.css`. In this case your custom CSS may not be applied at all.

**Comment by coffeeCowLu** [comment]
> Hi, in your preamble you added `ccs: styles.css` instead of `css: styles.css`. In this case your custom CSS may not be applied at all.

My stupid mistake, thank you very much for your kind reply.
