### ISSUE TITLE
Adding literal block scalar (|) in YAML title results in smaller than expected font size in readthedown document

### ISSUE THREAD

**Issue by OXB-github** [juba/rmdformats#87]
If I add a '|' (a literal block scalar) at the beginning of my title the font size of the multi line title appears too small:
```---
title: |
  Testing  
  Testing
author:
```

whereas if I just have a single line title, the font size is the size I expect.

The reason I'm doing this is so I can insert a logo as explained here:
[https://bookdown.org/yihui/rmarkdown-cookbook/latex-logo.html](https://bookdown.org/yihui/rmarkdown-cookbook/latex-logo.html)

I'm not really an expert in html and CSS so haven't delved too much into the readthedown template files to see why this might be occurring.

I'm using rmdformats version 1.0.1

**Comment by juba** [comment]
I didn't know this tip ! Font size should be fixed in the development version, I hope it will solve your use case.

**Comment by OXB-github** [comment]
Yes its fixed in the latest version, thankyou!
