### ISSUE TITLE
readthedown incompatibility with DT (DataTables)

### ISSUE THREAD

**Issue by OXB-github** [juba/rmdformats#88]
If I knit a readthedown document containing a DT::datatable with style="bootstrap" I see 2 sets of overlaid ordering icons at the top of each column as shown in the picture below:
![Screenshot from 2021-01-04 16-10-21](https://user-images.githubusercontent.com/59445811/103554848-76871000-4ea7-11eb-8206-996e0758ed10.png)

This suggests to me that readthedown is using the default datatable icons as well as the theme icons for column reordering.

If, on the other hand, I use the "default" DT::datatable style then I dont have this problem, but instead have issues with the buttons, the pagination drop-down box, and filter box all being crammed on top of one another at the top left of the table which looks a bit unsightly (no screenshot shown).

This second problem must relate to how readthedown overides default positioning of these elements (which I wish it didn't).

Hope this is enough info for you to go on.

**Comment by juba** [comment]
I don't see the problem you mention when adding buttons to the default style : 

```r
DT::datatable(
  iris, extensions = 'Buttons', options = list(
    dom = 'Blfrtip',
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
  )
)
```
Would you have a reproducible example ?

When you using `style = "bootstrap"`, and I don't have the overlapping icons problem, but the buttons and pagination layout is indeed broken. By the way I don't override the default positioning of these elements, but the interactions between the different CSS used in the templates and in the objects created by packages like `DT` are quite complex and I don't have the time to test everything.

**Comment by OXB-github** [comment]
OK so I created a new session and attempted to reproduce this with a minimal data set (Iris) and partially solved the issue(s).

The issue with the 2 sets of overlapping ordering icons was because I had a number of DTs in the same .rmd, some with the "default" style and some with "bootstrap", and when this document is knit it combines both styles. So I changed everything to style="default" and its fine now.

The other issue with the clustered buttons etc only occurs with style="bootstrap" (not as stated in my original post with style="default"). I believe my error was because I have tables with mixed styles in my document and assumed that my tables were using the default style (when in fact the clustering is caused by the bootstrap style).

I have switched to default DT style so you can close this issue if you like. Thanks for replying to this and the other one so quickly.
