### ISSUE TITLE
Gallery view for image lightbox

### ISSUE THREAD

**Issue by noamross** [juba/rmdformats#9]
It would be great to have an option for images to pop up with gallery view (http://dimsemenov.com/plugins/magnific-popup/documentation.html#gallery), or even full-screen gallery view.  This is helpful because it allows any Rmd doc to instantly convert to a presentation where one can flip though figures.  Ideally  one could set this via an option in the YAML header, like so:

    output:
      rmdformats:html_docco:
        gallery: yes

**Comment by juba** [comment]
I just pushed several commits which add two new options for all three formats : 
- `lightbox` allows to toggle images thumbnailing with lightbox effect
- when `lightbox` is true, `gallery` toggles navigation between images 

So you should be able to use something like :

```
output:
  rmdformats:html_docco:
    lightbox: true
    gallery: true
```

Is this the feature you had in mind ?

Thanks for the suggestion !

**Comment by noamross** [comment]
Yes, great!  I note that for my own use I modify the CSS so that the "thumbnail" images are full-width of the content.  This is because I like having the page readable as-is, but use the lightbox so that readers can have a closer look or I can present the figures at maximum size.  No need to change anything, but that's a use-case to consider.

**Comment by juba** [comment]
You're right, seems like a perfectly legitimate use case.

I just added a `thumbnails` option to toggle thumbnailing for content images. I think that together with `lightbox` and `gallery` it should give some flexibility on image displaying.

Thanks for the suggestions, and don't hesitate if you see other not covered use cases.
