### ISSUE TITLE
material knitting adds two tabs and a space at the beginning of new lines in code fences

### ISSUE THREAD

**Issue by homerhanumat** [juba/rmdformats#90]
When using `rmdformats::material`, I find that in the process of conversion from markdown to html, two tabs and a space are added to the second and all subsequent lines in a code fence.  Here is a minimal example:

<pre>
---
title: "Test"
output:
  rmdformats::material:
---

# A Section

```
a line
another line
```
</pre>

Using development version 1.0.2, with current CRAN versions of knitr, rmarkdown and htmltools.  Knitting in R Studio 1.4.1103:

```
rmarkdown::pandoc_version()
```

gives 2.11.2.

**Comment by juba** [comment]
Hi,

Strangely I cannot directly reproduce the issue but I think I know where it comes from. Could you please check if the issue is fixed for you in the development version ?

Thanks for taking the time to report the issue.

**Comment by homerhanumat** [comment]
Your commit fixed it. Thanks!
