### ISSUE TITLE
Combine Multiple Rmd Files

### ISSUE THREAD

**Issue by nick-ulle** [juba/rmdformats#93]
Is it possible to use rmdformats to combine several Rmd files into a single knitted document?

My colleagues and I currently use rmdformats for a [course reader](https://ucdavisdatalab.github.io/adventures_in_data_science/), but keeping all of the content in a single Rmd is starting to become unwieldy. We'd like to split the chapters into separate Rmd files, but as far as I can tell, the docs don't mention a way to combine separate files when knitting.

I see [bookdown supports this by default](https://bookdown.org/yihui/bookdown/usage.html), and I'm able to knit with `bookdown::render_book` instead of `rmarkdown::render`, but `render_book` ignores my `output_dir` setting. I'm not sure if that's due to bookdown or rmdformats, but get the impression this approach wasn't intended by the authors of either package.

Thanks for any help with this!

**Comment by juba** [comment]
Hi,

Yes, I think that's possible with Rmarkdown documents, this is described here : 

https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html

In fact I use this feature to share the main content between the different templates vignettes : 

https://github.com/juba/rmdformats/blob/master/vignettes/examples/readthedown.Rmd

Hope that helps !

**Comment by juba** [comment]
Just a quick follow-up : `bookdown` may be more suitable for long documents, as users won't have to load everything at once, and you get some additional features such as searching, pdf/epub downloads, etc. 

`output_dir` should be supported by bookdown, but you'll have to put the configuration in a `_bookdown.yml` file : 

https://bookdown.org/yihui/bookdown/configuration.html

Unfortunately I don't think `rmdformats` will work with `bookdown`, though.

**Comment by nick-ulle** [comment]
Thanks, that's helpful.

**Comment by nick-ulle** [comment]
About `output_dir`, I meant I tried using `render_book` with the output set to `rmdformats::readthedown`. The file still knits correctly, but the `output_dir` argument to `render_book` gets ignored. But I realize this combination is probably not what you or the bookdown devs had in mind.

**Comment by juba** [comment]
Yes, I'm not surprised it doesn't work, `bookdown` doesn't directly use RMarkdown output formats, it first renders with `bookdown::gitbook`, which would not be called when using `rmdformats`.
