### ISSUE TITLE
DT::datatable() background color of table header

### ISSUE THREAD

**Issue by DiegoNOB** [juba/rmdformats#97]
[As shown here in the DT documentation](https://rstudio.github.io/DT/options.html), it is possible to change the background color of a table header produced with `DT::datatable()` by adding some JavaScript code. It works fine when I knit to html, but I can't get it to work if I use the `readthedown` theme.

Minimal reproducible example:

````
---
title: "Untitled"
output: rmdformats::readthedown
---

```{r}
library(DT)

datatable(head(iris, 20), options = list(
  initComplete = JS(
    "function(settings, json) {",
    "$(this.api().table().header()).css({'background-color': '#000', 'color': '#fff'});",
    "}")
))
```
````

<img width="319" alt="rmd" src="https://user-images.githubusercontent.com/10402325/108081126-5ffbd900-704f-11eb-8719-01a9020bb8ce.png">

Any help would be much appreciated. Thanks!

Session info:

````
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Argentina.1252  LC_CTYPE=Spanish_Argentina.1252   
[3] LC_MONETARY=Spanish_Argentina.1252 LC_NUMERIC=C                      
[5] LC_TIME=Spanish_Argentina.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DT_0.17

loaded via a namespace (and not attached):
 [1] htmlwidgets_1.5.3 compiler_4.0.3    magrittr_2.0.1    bookdown_0.21     htmltools_0.5.1.1
 [6] tools_4.0.3       rstudioapi_0.13   yaml_2.2.1        rmarkdown_2.6     knitr_1.31       
[11] rmdformats_1.0.2  xfun_0.20         digest_0.6.27     rlang_0.4.10      evaluate_0.14    
````

**Comment by juba** [comment]
I tried to redefine styles no to override dataTable's `background-color` properties, and I think it should work now, at least for your example. It is possible that other customization would be in conflict with readthedown's CSS though.

Thanks for reporting the issue with reproducible example !

**Comment by DiegoNOB** [comment]
Background color in datatable header is now working as expected. Thanks so much!!!
